### ISSUE TITLE
[BUG]Forecast error using OWM Forecast setting

### ISSUE THREAD

**Issue by endmarsfr** [Daveiano/weewx-wdc#100]
Hello

I had this error with OWM forecast, day icons seems to be not found.

**_"/home/weewx/bin/user/weewx_wdc_forecast.py", line 46, in get_day_icon**
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      if summary["pop"].raw > 65:
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****  TypeError: '>' **not supported between instances of 'NoneType' and 'int'__**

Error when setting OWM in skin.conf
    [[forecast_table_settings]]
        source = **OWM**

**but work fine if I set WU**
    [[forecast_table_settings]]
        source = WU

**even if WU and OWM are well configured and started in weewx.log**

_nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: Zambretti: forecast version 3.4.0b12
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: Zambretti: interval=600 max_age=604800 winddir_period=1800 pressure_period=10800 hemisphere=NORTH lower_pressure=950.0 upper_pressure=1050.0
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: **WU: forecast version 3.4.0b12**
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: **WU: interval=10800 max_age=604800 api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXc7e4 geocode=48.575972,2.224319**
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: **OWM: forecast version 3.4.0b12**
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: **OWM: interval=10800 max_age=604800 api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXX3a20 location=48.575972,2.224319 fc=5day3hour_**__

**error log :**

_nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_body_classic_inc.py", line 103, in respond
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_forecast_inc.py", line 222, in respond
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_forecast_table_inc.py", line 659, in respond
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/user/weewx_wdc_forecast.py", line 46, in get_day_icon
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      if summary["pop"].raw > 65:
nov. 19 18:26:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****  TypeError: '>' not supported between instances of 'NoneType' and 'int'
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/index.html.tmpl failed with exception '<class 'TypeError'>'
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/index.html.tmpl
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: **** Reason: '>' not supported between instances of 'NoneType' and 'int'
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 348, in generate
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_index_html_tmpl.py", line 173, in respond
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_body_classic_inc.py", line 103, in respond
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_forecast_inc.py", line 222, in respond
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_forecast_table_inc.py", line 659, in respond
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/user/weewx_wdc_forecast.py", line 46, in get_day_icon
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****      if summary["pop"].raw > 65:
nov. 19 18:27:48 radio weewxd[740]: weewx[740] ERROR weewx.cheetahgenerator: ****  TypeError: '>' not supported between instances of 'NoneType' and 'int'_

**Weewx start log :**

_-- Logs begin at Thu 2019-02-14 11:12:02 CET. --
nov. 19 18:33:07 radio weewxd[3185]: weewx[3185] INFO __main__: PID file is /var/run/weewx.pid
nov. 19 18:33:07 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Loading station type Interceptor (user.interceptor)
nov. 19 18:33:08 radio weewx[3174]: Starting weewx weather system: weewx.
nov. 19 18:33:08 radio systemd[1]: Started LSB: weewx weather system.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: driver version is 0.60
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: device type: wu-client
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: hardware name: weatherstation via interceptor
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: mode is sniff
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: sniff iface=wlan0 promiscuous=0
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: sniff filter 'src xxxxxx  and dst port 80'
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: pypcap (1.3.0)
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.interceptor: sensor map: {'pressure': 'pressure', 'barometer': 'barometer', 'outHumidity': 'humidity_out', 'inHumidity': 'humidity_in', 'outTemp': 'temperature_out', 'inTemp': 'temperature_in', 'windSpeed': 'wind_speed', 'windGust': 'wind_gust', 'windDir': 'wind_dir', 'windGustDir': 'wind_gust_dir', 'radiation': 'solar_radiation', 'dewpoint': 'dewpoint', 'windchill': 'windchill', 'rain': 'rain', 'rainRate': 'rain_rate', 'UV': 'uv', 'txBatteryStatus': 'battery', 'extraTemp1': 'temperature_1', 'extraTemp2': 'temperature_2', 'extraTemp3': 'temperature_3', 'extraHumid1': 'humidity_1', 'extraHumid2': 'humidity_2', 'soilTemp1': 'soil_temperature_1', 'soilTemp2': 'soil_temperature_2', 'soilMoist1': 'soil_moisture_1', 'soilMoist2': 'soil_moisture_2', 'soilMoist3': 'soil_moisture_3', 'soilMoist4': 'soil_moisture_4', 'leafWet1': 'leafwetness_1', 'leafWet2': 'leafwetness_2', 'pm2_5': 'pm2_5', 'extraTemp4': 'temperature_4', 'extraTemp5': 'temperature_5', 'extraTemp6': 'temperature_6', 'extraTemp7': 'temperature_7', 'extraTemp8': 'temperature_8', 'extraHumid3': 'humidity_3', 'extraHumid4': 'humidity_4', 'extraHumid5': 'humidity_5', 'extraHumid6': 'humidity_6', 'extraHumid7': 'humidity_7', 'extraHumid8': 'humidity_8', 'soilTemp3': 'soil_temperature_3', 'soilTemp4': 'soil_temperature_4'}
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: StdConvert target unit is 0x10
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Archive will use data binding wx_binding
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Record generation will be attempted in 'hardware'
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Using archive interval of 60 seconds (specified in weewx configuration)
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: Zambretti: forecast version 3.4.0b12
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: Zambretti: interval=600 max_age=604800 winddir_period=1800 pressure_period=10800 hemisphere=NORTH lower_pressure=950.0 upper_pressure=1050.0
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: WU: forecast version 3.4.0b12
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: WU: interval=10800 max_age=604800 api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXc7e4 geocode=48.575972,2.224319
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: OWM: forecast version 3.4.0b12
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO user.forecast: MainThread: OWM: interval=10800 max_age=604800 api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXX3a20 location=48.575972,2.224319 fc=5day3hour
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: StationRegistry: Registration not requested.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: Wunderground: Posting not enabled.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: PWSweather: Posting not enabled.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: CWOP: Posting not enabled.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: WOW: Posting not enabled.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.restx: AWEKAS: Posting not enabled.
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: 'pyephem' detected, extended almanac data is available
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO __main__: Starting up weewx version 4.9.1
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.manager: Starting backfill of daily summaries
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.manager: Daily summaries up to date
nov. 19 18:33:08 radio weewxd[3190]: weewx[3190] INFO weewx.engine: Starting main packet loop._

**Comment by Daveiano** [comment]
Hello, thank you for heading out and providing this much information!

Last week, while working on the next version, especially on #95, I already noticed this issue and solved it already (committed in 4fd5da7833a04d85cfd80ff1ea010e6f7335eb21).

It will be included in the next [3.0.0 release](https://github.com/Daveiano/weewx-wdc/milestone/12).
