### ISSUE TITLE
Wind direction aggregation

### ISSUE THREAD

**Issue by Jterrettaz** [Daveiano/weewx-wdc#119]
Hello,
Currently, the wind direction is aggregated as average (avg). As mentioned in the weewx documentation:
`Not a very useful quantity. This is the strict, arithmetic average of all the compass wind directions. If the wind blows at 350° for two hours then at 10° for two hours, then the scalar average wind direction will be 180° — probably not what you expect, nor want.`
Since weewx V4.9.0, there is a new aggregation type "vecdir" to address this problem :  use xxxx.wind.vecdir instead of xxxx.winDir.avg

We had here these last days an episode with north wind, with wind directions oscillating from WNW to NE.  
with the current version of wdc, the weekly chart and windrose are :
<img width="1270" alt="windir avg" src="https://user-images.githubusercontent.com/2173471/222134831-bae43bd6-cc4c-4e3f-a26b-2b217e4127f2.png">
showing mostly winds from SE !
I changed  ( in my own modified wdc files)  the aggregation to wind.vecdir, and the result is this time representative of the wind direction observed during the period : 
<img width="1250" alt="wind vecdir" src="https://user-images.githubusercontent.com/2173471/222135368-d9f67bc3-c791-4431-8079-18d4cbbd9713.png">

**Comment by Daveiano** [comment]
Great catch! During a recent series of storm days in the last month, I also noticed these wrong chart plots regarding the wind direction.

I did not notice that there was a new aggregation_type `vecdir` coming with v4.9. 

Did you create your changes against the 2.x or 3.x branch? I would be happy to include this as a PR :)

Relevant docs: 
https://www.weewx.com/docs/customizing.htm#Wind
https://github.com/weewx/weewx/issues/800

**Comment by Jterrettaz** [comment]
My changes were against the 2.x branch.  Should I open a pull request and insert there my changes ?

**Comment by Daveiano** [comment]
The current branch is 3.x which got a really heavy re-write compared to 2.x. If it is no problem for you you can open a PR for 2.x. I will try to merge it back into 3.x

**Comment by Daveiano** [comment]
Merged into 2.x in 6ff8bfd1d4e5a8e9da5aadcd11135c7a714ad893

Merged into 3.x in a827f483a4d1312bc4b8c927dbec3108ce1a6bf9

Some improvements/updates in 3933f4276ab27e443a3f80a34c3f161537437256

Thank you very much for your contribution! It would be great if you could test it out in the new v3.0.0 (which should be released by the end of the next week).

**Comment by Jterrettaz** [comment]
Yes, I can test the current 3.X version. Could you please send me the built js and css files of the last version ?

**Comment by Daveiano** [comment]
Please be patient :)

v3.0.0 will be released within the next week. There are a few wiki pages that need to be updated before the release.

**Comment by Daveiano** [comment]
@Jterrettaz Sorry, I totally forgot to say that v3.0.0 is out now, you can test it: https://github.com/Daveiano/weewx-wdc/releases/tag/v3.0.0
