### ISSUE TITLE
Archive HTML not working

### ISSUE THREAD

**Issue by DarrylP796** [Daveiano/weewx-wdc#130]
Dave,

I hate to ask for help again, but I've been working the issue and can't get it resolved.

I had the issue where the base_path in WDC's skin.conf needed to be modified to include /weewx/ . This made my main HTML page work.

The problem I still face is that none of the archived data HTML pages work.  They all look like the main page used to before the base_path change.

Any ideas? The archive data is there and the Seasons report, when enabled, works well.  Just no HTML archive data with WDC.

Regards,

Darryl

**Comment by Daveiano** [comment]
Hi Darryl,

it's no problem, I am happy to help you!

You need to remove all archive pages (day, month, year) after the `base_path` change, because these pages are only generated once, they are not updated after the change.

So something like

```
sudo rm -rf /var/www/html/weewx/day-archive/*
sudo rm -rf /var/www/html/weewx/year*
sudo rm -rf /var/www/html/weewx/month*
```

and a new report run should solve this.

**Comment by DarrylP796** [comment]
Thank you! Working well.

Darryl

**Comment by Daveiano** [comment]
You are welcome, happy to help!
