### ISSUE TITLE
[BUG] Adding 'Voltage' observations make icons disappear on today page

### ISSUE THREAD

**Issue by Nkawu** [Daveiano/weewx-wdc#144]
Using v3.1.1 of the skin on weewx v4.10.2. When I add a new diagram, e.g. consBatteryVoltage, black rectangles show up on the Today page. The icons still display fine on the Week/Month/Year pages.

<img width="923" alt="Screen Shot 2023-03-29 at 3 13 49 PM" src="https://user-images.githubusercontent.com/1527620/228680441-bcdd6701-30dc-4fa0-9967-19f9b1edec44.png">

Here is a trimmed down version of what I have in my `weewx.conf` file:

```
    [[WdcReport]]
        skin = weewx-wdc
        enable = true
        HTML_ROOT = public_html/weewx-wdc
        lang = en
        [[[Extras]]]
            base_path = /weewx-wdc/
        [[[DisplayOptions]]]
            [[[[diagrams]]]]
                [[[[[day]]]]]
                    aggregate_interval = 1800 # 30 minutes
                    [[[[[[observations]]]]]]
                        [[[[[[[tempdew]]]]]]]
                        [[[[[[[outHumidity]]]]]]]
                        [[[[[[[barometer]]]]]]]
                        [[[[[[[windchill_heatindex]]]]]]]
                        [[[[[[[wind]]]]]]]
                        [[[[[[[windDir]]]]]]]
                        [[[[[[[windRose]]]]]]]
                        [[[[[[[rain]]]]]]]
                            aggregate_interval = 7200  # 2 hours
                        [[[[[[[rainRate]]]]]]]
                        [[[[[[[UV]]]]]]]
                        [[[[[[[ET]]]]]]]
                            aggregate_interval = 7200  # 2 hours
                        [[[[[[[radiation]]]]]]]
                        [[[[[[[cloudbase]]]]]]]
                        [[[[[[[appTemp]]]]]]]
                        [[[[[[[consBatteryVoltage]]]]]]]
```

There are no errors in the log.

I have not yet tried to see if the same happens when I add the changes directly to `skins/weewx-wdc/skin.conf`

**Comment by Daveiano** [comment]
Is your website public accessibly so I could have a look?

**Comment by Nkawu** [comment]
> Is your website public accessibly so I could have a look?

No unfortunately just on my private network. Is there something I can check for you?

Very strange, the moment I comment out the entire `[[[[diagrams]]]]` block, the icons render again. I also tried editing the `[[[day]]]` block directly in `skins/weewx-wdc/skin.conf`, with the same result.

**Comment by Daveiano** [comment]
~~Open the page in your browser and save the page (hit STRG + S if on win or have a look here: https://www.makeuseof.com/tag/save-complete-webpage-offline-reading/)~~

~~Please attach the output to your comment so I can have a look~~

I just found it: it`s a bug with the voltage icon - I will have a look!

**Comment by Nkawu** [comment]
Zipped up page attached:

[WDC_Index.zip](https://github.com/Daveiano/weewx-wdc/files/11106471/WDC_Index.zip)

**Comment by Daveiano** [comment]
Could you please test this out:

Change the content of `skins/weewx-wdc/includes/icons/voltage.svg` to

```
<svg
  width="32"
  height="32"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 32 32"
>
  <defs>
    <style>
      .cls-1 {
        fill: none;
      }
    </style>
  </defs>
  <title>battery--charging</title>
  <path
    d="M27,11H26V10a2,2,0,0,0-2-2H20v2h4v3h3v6H24v3H19v2h5a2,2,0,0,0,2-2V21h1a2,2,0,0,0,2-2V13A2,2,0,0,0,27,11Z"
  />
  <path d="M11,22H6V10h6V8H6a2,2,0,0,0-2,2V22a2,2,0,0,0,2,2h5Z" />
  <polygon
    points="14.81 23.58 13.19 22.42 17.06 17 9.37 17 16.22 8.38 17.78 9.62 13.51 15 20.94 15 14.81 23.58"
  />
  <rect
    data-name="&lt;Transparent Rectangle&gt;"
    class="cls-1"
    width="32"
    height="32"
  />
</svg>

```

**Comment by Nkawu** [comment]
That worked - all icons render now! Thank you for the quick response.

**Comment by Daveiano** [comment]
You are welcome, the fix will be included in the next release!
