### ISSUE TITLE
[BUG] Doesn't Honor HTML_ROOT base_path Needed

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#145]
**Describe the bug**
I see that the generated pages are not displayed, example week.html
I have a path that is a subdirectory to the root.
/home/weather/wdc

Though I see the files have been created in that directory, the URLs are incorrect
Click on left panel Week http://wx-tab.lan/week.html is what is generated, which is a 404.
I have tried different combinations for base_path with no change.

**To Reproduce**
Use a path with subdirectory as HTML_ROOT
Generate the report
View in browser.

**Expected behavior**
Site should display

**Comment by gary-hammer** [comment]
Attaching screenshot
![wdc](https://user-images.githubusercontent.com/12861605/229299863-843c1179-b3de-4539-b3ca-425a24a0c49e.png)

**Comment by gary-hammer** [comment]
I noticed a note on base_path in the wiki.
However, it isn't clear on what that should be

In my case the path is /home/weather/wdc

What should the base_path be set to?

Is there a reason that this skin can't use the HTML_ROOT as other skins do?

**Comment by Daveiano** [comment]
> In my case the path is /home/weather/wdc

The base is the path on your webserver, not on your filesystem. So for your setup, this should work:

`base_path=/wdc/`

since you are accessing the page via wx-tab.lan/wdc

> What should the base_path be set to?
Is there a reason that this skin can't use the HTML_ROOT as other skins do?

Could you give me an example of what other skins do with HTML_ROOT? Should be pretty similar to `base_path` except for the naming?

**Comment by Daveiano** [comment]
Sorry, I recognized `HTML_ROOT ` - thats the setting for where the generated files should go on your filesystem - a default weewx setting.

The skin uses `base_path` for generating links - which depends on the location of the generated skin on your webserver.

**Comment by gary-hammer** [comment]
> > What should the base_path be set to?
> > Is there a reason that this skin can't use the HTML_ROOT as other skins do?
> 
> Could you give me an example of what other skins do with HTML_ROOT? Should be pretty similar to `base_path` except for the naming?

-# Where the generated reports should go, relative to WEEWX_ROOT
    HTML_ROOT = /home/weather

[[Belchertown]]
        skin = Belchertown
        HTML_ROOT = /home/weather/belchertown
        enable = true

[[SeasonsReport]]
        # The SeasonsReport uses the 'Seasons' skin, which contains the
        # images, templates and plots for the report.
        skin = Seasons
        enable = true
        HTML_ROOT = /home/weather/seasons


If you are generating links, why not generate them off the HTML_ROOT? Then, users only have to specify in one place and not use filesystem vs web location to do so.

Both the stock Seasons skin and the 3rd party Belchertown skin have linked pages. Nothing but the HTML_ROOT is needed.

In any event, with the edit of the skin.conf with the correct value, all is well.
