### ISSUE TITLE
ModuleNotFoundError: No module named 'user.weewx_wdc_forecast'

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#152]
i updated my pi and updated weewx and weewx wdc.

After the update I ran wee_reports but as an error message I get the following:

root@weewx:~# wee_reports
Generating as of last timestamp in the database.
Using configuration file /etc/weewx/weewx.conf
Traceback (most recent call last):
   File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
     obj.start()
   File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
     self.run()
   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 166, in run
     self.init_extensions(gen_dict[section_name])
   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in init_extensions
     class = weeutil.weeutil.get_object(x)
   File "/usr/share/weewx/weeutil/weeutil.py", line 1335, in get_object
     mod = __import__(modules)
ModuleNotFoundError: No module named 'user.weewx_wdc_forecast'

Does anyone have an idea what this could be?

**Comment by Daveiano** [comment]
Just a quick guess because I am currently not on a PC: did you reuse your old skin.conf. If you upgraded from 2.x to 3.x there were a lot of changes in the configuration file.

If it is not this, I will have a look as soon as I can within the next week!

**Comment by Supergamerx3000** [comment]
Yes I use the old weewx.conf my old version of weewx was also version 3. How can I get a fresh weewx.conf file?

**Comment by Daveiano** [comment]
> Yes I use the old weewx.conf my old version of weewx was also version 3. How can I get a fresh weewx.conf file?

You mean skin.conf and weewx-wdc version 3, right? You can get a fresh file directly from the release: https://github.com/Daveiano/weewx-wdc/releases/download/v3.1.1/weewx-wdc-v3.1.1.zip

Could you please share your current skin.conf file so I can have a look? Please also share the complete `[[WdcReport]]` section from weewx.conf for further investigation.

**Comment by Supergamerx3000** [comment]
Here are my skin.conf:

# configuration file for the weewx-wdc skin
SKIN_NAME = Weather Data Center
SKIN_VERSION = 3.3.0

[ObservationBindings]
    [[custom_obs_1]]
        data_binding = extension_1_binding # eg wx_binding
        observation = obs_key # eg. outTemp
    [[custom_obs_2]]
        data_binding = extension_2_binding
        observation = another_obs_key

[Extras]
    # Only change this if the generated files are deployed to some
    # sub-folder of your web server.
    # E.g. If you are accessing your site via "http://my-weewx.com/weewx-wdc/"
    # the base_path should be "/weewx-wdc/".
    base_path = /

    # If activated the Fontpage (index.html) will be automatically be
    # refreshed in the browser every 300 seconds.
    #refresh_interval = 300

    # Show a link to the GitHub respository of this skin. Set to False to hide.
    github_link = True

    # The radar code. Full html allowed.
    #radar_html = ''
    # The Foreacst/Radar/Webcam section heading.
    #forecast_radar_heading = "Forecast & Recent radar"

    # Set to True to have the Forecast tile and the radar/externals tile to have the same width.
    # Default is forecast = 2/3 and radar tile = 1/3.
    forecast_radar_equal_width = False

    [[mqtt]]
        mqtt_websockets_enabled = 0
        mqtt_websockets_host = "localhost"
        mqtt_websockets_port = 9001
        mqtt_websockets_ssl = 0
        mqtt_websockets_topic = "weather/loop"

    # Include various external sources (eg. webcams) here.
    #[[externals]]
    #    description = 'This description will be shown at the Webcams/Externals page.
    #
    #    [[[current_backyard_image]]]
    #        source = '<img src="https://my-server.com/current/image.jpg" />'
    #        title = Current image
    #        title_long = "Webcam facing North"
    #        description = 'The image is updated every 80 seconds, nighttime every 100 seconds.'
    #        show_on_front = True
    #        show_on_page = True

    [[forecast_zambretti]]
        enable = False

    [[forecast_table_settings]]
        source = WU
        num_periods = 72
        num_days = 5
        show_hourly = 1
        show_day = 1
        show_date = 1
        show_outlook = 1
        show_temp = 1
        show_dewpoint = 0
        show_humidity = 0
        show_wind = 1
        show_tides = 0
        show_sun = 1
        show_moon = 1
        show_pop = 1
        show_precip = 1

    #[[weewx-DWD]]
    #   show_text_forecast = True
    #   text_forecast_VHDL = DWLG
    #   dwd_link = https://www.dwd.de/DE/wetter/wetterundklima_vorort/sachsen/sac_node.html
    #   show_pressure_map = True
    #   show_warning_map = True
    #   warning_map_filename = 'SchilderLZ.jpg'
    #   show_text_warnings = True
    #   show_warnings_on_front = XXX
    #   show_forecast = True
    #   mosmix_id = XXXX
    #   [[[forecast_table_settings]]]
    #       show_hourly = 1
    #       show_date = 1
    #       show_outlook = 1
    #       show_temp = 1
    #       show_dewpoint = 1
    #       show_pressure = 1
    #       show_wind= 1
    #       show_pop = 1
    #       show_precip = 1
    #       show_cloud_cover = 1
    #       show_sun_dur = 1
    #       carbon_icons = 0

[DisplayOptions]
    # 'alternative' or 'classic'.
    layout = 'alternative'

    # Date/Time localization for charts. Available locales: de-DE, en-US, en-GB, it-IT.
    # If not set, the value from weewx.conf (reports section) will be used. If lang = en, then en-US will be used (sorry GB!).
    #date_time_locale = en-US

    # These days will be shown on the year and statistics pages.
    climatological_days = rainDays, summerDays, hotDays, desertDays, tropicalNights, stormDays, iceDays, frostDays
    show_last_rain = True
    show_most_days_with_rain = True
    show_most_days_without_rain = True
    show_most_rain_within_one_day = True

    # What to show in the tables.
    table_tile_observations = outTemp, outHumidity, barometer, windSpeed, windGust, windDir, rain, rainRate, snowDepth, dewpoint, windchill, heatindex, UV, ET, radiation, appTemp, cloudbase, extraTemp1, extraHumid1, extraTemp2, extraHumid2, extraTemp3, extraHumid3, extraTemp4, extraHumid4, extraTemp5, extraHumid5, extraTemp6, extraHumid6, extraTemp7, extraHumid7, extraTemp8, extraHumid8

    # What to show for the stat tiles.
    stat_tile_observations = outTemp, outHumidity, barometer, windSpeed, windDir, windGust, windGustDir, windrun, rain, rainRate, snowDepth, dewpoint, windchill, heatindex, UV, ET, radiation, appTemp, cloudbase, extraTemp1, extraHumid1, extraTemp2, extraHumid2, extraTemp3, extraHumid3, extraTemp4, extraHumid4, extraTemp5, extraHumid5, extraTemp6, extraHumid6, extraTemp7, extraHumid7, extraTemp8, extraHumid8

    # Stat tiles: Min/Max/Sum settings.
    stat_tiles_show_min = outTemp, outHumidity, barometer, pressure, altimeter, snowDepth, heatindex, dewpoint, windchill, cloudbase, appTemp, rxCheckPercent, consBatteryVoltage
    stat_tiles_show_max = rainRate, hailRate, snowRate, UV
    stat_tiles_show_sum = rain, ET, hail, snow, lightning_strike_count, windrun

    # Stat tiles: show time when the min/max was reached.
    show_min_max_time_day = False
    show_min_max_time_yesterday = False
    show_min_max_time_week = False
    show_min_max_time_month = False

    # windDir as oridnals (N, E, S, W).
    stat_tile_winddir_ordinal = True
    diagram_tile_winddir_ordinal = True

    # Windrose.
    windRose_colors = "#f3cec9", "#e7a4b6", "#cd7eaf", "#a262a9", "#6f4d96", "#3d3b72"
    windRose_show_beaufort = True

    # Climatogram on year and statistics pages.
    climatogram_enable_stats = True
    climatogram_enable_year_stats = True

    # Sensor status page.
    sensor_stat_tile_observations = rxCheckPercent, signal1, signal2, signal3, signal4, signal5, signal6, signal7, signal8, consBatteryVoltage, heatingVoltage, supplyVoltage, referenceVoltage
    sensor_diagram_observations = rxCheckPercent, signal1, signal2, signal3, signal4, signal5, signal6, signal7, signal8, consBatteryVoltage, heatingVoltage, supplyVoltage, referenceVoltage
    sensor_table_observations = rxCheckPercent, signal1, signal2, signal3, signal4, signal5, signal6, signal7, signal8, consBatteryVoltage, heatingVoltage, supplyVoltage, referenceVoltage
    sensor_battery_status = outTempBatteryStatus, inTempBatteryStatus, rainBatteryStatus, hailBatteryStatus, snowBatteryStatus, windBatteryStatus, uvBatteryStatus, txBatteryStatus, batteryStatus1, batteryStatus2, batteryStatus3, batteryStatus4, batteryStatus5, batteryStatus6, batteryStatus7, batteryStatus8
    # Time period of diagrams (day, week, month or year).
    sensor_diagram_period = week

    # Computer monitor page.
    computer_monitor_stat_tile_observations = cpu_user, cpu_system, cpu_temp, load1, load5, load15, mem_used, mem_free, net_eth0_rbytes, net_eth0_rpackets, net_eth0_tbytes, net_eth0_tpackets, net_wlan0_rbytes, net_wlan0_rpackets, net_wlan0_tbytes, net_wlan0_tpackets, proc_active, proc_total
    computer_monitor_diagram_observations = cpu_user, cpu_system, cpu_temp, load1, mem_used, proc_active, net_eth0_rbytes, net_eth0_tbytes, net_wlan0_rbytes, net_wlan0_tbytes
    computer_monitor_table_observations = cpu_user, cpu_system, cpu_temp, load1, load5, load15, mem_used, mem_free, net_eth0_rbytes, net_eth0_rpackets, net_eth0_tbytes, net_eth0_tpackets, net_wlan0_rbytes, net_wlan0_rpackets, net_wlan0_tbytes, net_wlan0_tpackets, proc_active, proc_total
    computer_monitor_diagram_period = week

    # Only applies when using the alternative layout.
    # One of 'before' or 'after'.
    gauges_display = before
    # One of small, medium or large.
    gauges_size = medium

    [[Gauges]]
        tick_number = 7
        arc = 1.2
        offset = 20
        # normal or invert
        mode = normal
        color_scheme = interpolateRdBu
        invert_color_scheme = 1

    # ONLY enable these if you have weewx-xaggs installed!
    #[[stat_tiles_xaggs]]
    #    [[[outTemp]]]
    #        aggregate_types = historical_max, historical_min, historical_avg, avg_ge_1, avg_ge_2, avg_ge_3
    #        avg_ge_1 = 5.0, 'degree_C', 'group_temperature'
    #        avg_ge_2 = 10.0, 'degree_C', 'group_temperature'
    #        avg_ge_3 = 15.0, 'degree_C', 'group_temperature'
    #        show_extra_row = False
    #        avg_context = year, alltime

    [[Icons]]
        #rain = "includes/icons/barometer.svg"

    #[[Rounding]]
        #dewpoint = 3

    [[tables]]
        #[[[Rounding]]]
            #outTemp = 3
        [[[day]]]
            aggregate_interval = 3600  # 1 hour
        [[[week]]]
            aggregate_interval = 21600  # 6 hours
        [[[month]]]
            aggregate_interval = 43200  # 12 hours
        [[[year]]]
            aggregate_interval = 86400  # 1 day
        [[[alltime]]]
            aggregate_interval = 86400  # 1 day

    [[diagrams]]
        #[[[Rounding]]]
            #barometer = 3

        [[[combined_observations]]]
            [[[[climatogram_year]]]]
                label = "Climatogram"
                curve="natural"
                aggregate_interval = month
                bottom_date_time_format = "%b"
                tooltip_date_time_format = "%B"
                [[[[[obs]]]]]
                    [[[[[[rain]]]]]]
                        observation = "rain"
                    [[[[[[outTemp]]]]]]
                        observation = "outTemp"

            [[[[climatogram_statistics]]]]
                label = "Climatogram"
                curve="natural"
                aggregate_interval = year
                bottom_date_time_format = "%Y"
                tooltip_date_time_format = "%Y"
                [[[[[obs]]]]]
                    [[[[[[rain]]]]]]
                        observation = "rain"
                    [[[[[[outTemp]]]]]]
                        observation = "outTemp"

            [[[[temp_min_max_avg]]]]
                label = "Temperature Min/Max/Avg"
                pointSize = 3
                yScaleOffset = 0.5
                markerValue = 0
                markerColor = "#00BFFF"
                [[[[[obs]]]]]
                    [[[[[[outTemp_min]]]]]]
                        observation = "outTemp"
                        aggregate_type = "min"
                        color = "#0198E1"
                    [[[[[[outTemp_average]]]]]]
                        observation = "outTemp"
                        aggregate_type = "avg"
                        color = "#666666"
                    [[[[[[outTemp_max]]]]]]
                        observation = "outTemp"
                        aggregate_type = "max"
                        color = "#8B0000"

            [[[[tempdew]]]]
                label = 'Temperature / Dewpoint'
                markerValue = 0
                markerColor = "#00BFFF"
                [[[[[obs]]]]]
                    [[[[[[temp]]]]]]
                        observation = "outTemp"
                    [[[[[[dew]]]]]]
                        observation = "dewpoint"
                        color = "#5F9EA0"

            [[[[windchill_heatindex]]]]
                label = 'Windchill / Heatindex'
                yScaleOffset = 0.5
                markerValue = 0
                markerColor = "#00BFFF"
                [[[[[obs]]]]]
                    [[[[[[chill]]]]]]
                        observation = "windchill"
                        color = '#0099CC'
                    [[[[[[heat]]]]]]
                        observation = "heatindex"
                        color = '#610000'

            [[[[wind]]]]
                label = 'Wind speed / Gust speed'
                yScaleMin = 0
                enableArea = True
                areaOpacity = 0.5
                curve = linear
                [[[[[obs]]]]]
                    [[[[[[gust]]]]]]
                        observation = "windGust"
                        color = "#666666"
                    [[[[[[speed]]]]]]
                        observation = "windSpeed"
                        color = "#ffc000"

        # Diagram-type specific settings.
        [[[line]]]
            lineWidth = 2
            pointSize = 5
            isInteractive = True
            enablePoints = True
            enableCrosshair = True
            yScaleOffset = 3
            enableArea = False
            areaOpacity = 0.07
            # @see https://github.com/Daveiano/weewx-wdc/wiki/Configuration#diagrams, at "curve".
            curve = "natural"
        [[[bar]]]
            enableLabel = False
            isInteractive = True
            enableCrosshair = True
            yScaleOffset = 3

        # Observation specific settings.
        [[[outTemp]]]
            type = line
            color = "#8B0000"
        [[[dewpoint]]]
            type = line
            color = "#5F9EA0"
        [[[outHumidity]]]
            yScaleMin = 0
            yScaleMax = 103
            type = line
            enableArea = True
            color = "#0099CC"
        [[[pressure]]]
            yScaleOffset = 1
            type = line
            enableArea = True
            color = "#666666"
        [[[barometer]]]
            yScaleOffset = 1
            type = line
            enableArea = True
            color = "#666666"
        [[[altimeter]]]
            yScaleOffset = 1
            type = line
            enableArea = True
            color = "#666666"
        [[[windchill]]]
            type = line
            color = "#0099CC"
        [[[heatindex]]]
            type = line
            color = "#610000"
        [[[windDir]]]
            curve = "basis"
            lineWidth = 0
            yScaleMin = 0
            yScaleMax = 360
            type = line
            color = "#161616"
        [[[windSpeed]]]
            yScaleMin = 0
            type = line
            enableArea = True
            color = "#ffc000"
        [[[windGust]]]
            aggregate_type = "max"
            yScaleMin = 0
            type = line
            enableArea = True
            color = "#666666"
        [[[rain]]]
            aggregate_type = "sum"
            yScaleMin = 0
            yScaleOffset = 0.25
            type = bar
            color = "#0198E1"
        [[[rainRate]]]
            aggregate_type = "max"
            curve = "linear"
            yScaleMin = 0
            yScaleOffset = 0.25
            type = line
            color = "#0a6794"
        [[[UV]]]
            aggregate_type = "max"
            curve = "step"
            yScaleMin = 0
            yScaleOffset = 1
            type = line
            enableArea = True
            color = "#e61919"
        [[[ET]]]
            aggregate_type = "sum"
            yScaleMin = 0
            yScaleOffset = 0.02
            type = bar
            color = "#E97451"
        [[[radiation]]]
            curve = "basis"
            yScaleMin = 0
            type = line
            enableArea = True
            color = "#ff8c00"
        [[[cloudbase]]]
            yScaleMin = 0
            yScaleOffset = 300
            type = line
            enableArea = True
            color = "#92b6f0"
        [[[appTemp]]]
            type = line
            color = "#C41E3A"
            markerValue = 0
            markerColor = "#00BFFF"
        [[[rxCheckPercent]]]
            yScaleMax = 100
            color = "#990033"
        [[[consBatteryVoltage]]]
            yScaleOffset = 0.25
            color = "#666699"
        [[[heatingVoltage]]]
            yScaleOffset = 0.25
        [[[supplyVoltage]]]
            yScaleOffset = 0.25
        [[[referenceVoltage]]]
            yScaleOffset = 0.25


        # Set which diagrams you want to see on the day, week month, etc pages.
        # Note for alltime: if aggregate_interval is not set,
        # it will be calculated automatically based on the number of days/records.
        [[[day]]]
            aggregate_interval = 1800 # 30 minutes
            bottom_date_time_format = "%H:%M"
            tooltip_date_time_format = "%x %X"
            [[[[observations]]]]
                [[[[[tempdew]]]]]
                [[[[[outHumidity]]]]]
                [[[[[barometer]]]]]
                [[[[[windchill_heatindex]]]]]
                [[[[[wind]]]]]
                [[[[[windDir]]]]]
                [[[[[windRose]]]]]
                [[[[[rain]]]]]
                    aggregate_interval = 7200  # 2 hours
                    tooltip_date_time_format = "%X"
                [[[[[rainRate]]]]]
                [[[[[UV]]]]]
                [[[[[ET]]]]]
                    aggregate_interval = 7200  # 2 hours
                    tooltip_date_time_format = "%X"
                [[[[[radiation]]]]]
                [[[[[cloudbase]]]]]
                [[[[[appTemp]]]]]

        [[[week]]]
            aggregate_interval = 7200  # 2 hours
            bottom_date_time_format = "%m/%d"
            tooltip_date_time_format = "%x %X"
            [[[[observations]]]]
                [[[[[tempdew]]]]]
                [[[[[outHumidity]]]]]
                [[[[[barometer]]]]]
                [[[[[windchill_heatindex]]]]]
                [[[[[wind]]]]]
                [[[[[windDir]]]]]
                [[[[[windRose]]]]]
                [[[[[rain]]]]]
                    aggregate_interval = 86400  # 1 day
                    tooltip_date_time_format = "%x"
                [[[[[rainRate]]]]]
                [[[[[UV]]]]]
                [[[[[ET]]]]]
                    aggregate_interval = 86400  # 1 day
                    tooltip_date_time_format = "%x"
                [[[[[radiation]]]]]
                [[[[[cloudbase]]]]]
                [[[[[appTemp]]]]]

        [[[month]]]
            aggregate_interval = 21600  # 6 hours
            bottom_date_time_format = "%m/%d"
            tooltip_date_time_format = "%x %X"
            [[[[observations]]]]
                [[[[[temp_min_max_avg]]]]]
                [[[[[tempdew]]]]]
                [[[[[outHumidity]]]]]
                [[[[[barometer]]]]]
                [[[[[windchill_heatindex]]]]]
                [[[[[wind]]]]]
                [[[[[windDir]]]]]
                [[[[[windRose]]]]]
                [[[[[rain]]]]]
                    aggregate_interval = 172800  # 2 days
                    tooltip_date_time_format = "%x"
                [[[[[rainRate]]]]]
                [[[[[UV]]]]]
                [[[[[ET]]]]]
                    aggregate_interval = 172800  # 2 days
                    tooltip_date_time_format = "%x"
                [[[[[radiation]]]]]
                [[[[[cloudbase]]]]]
                [[[[[appTemp]]]]]

        [[[year]]]
            aggregate_interval = 172800  # 2 days
            bottom_date_time_format = "%m/%d"
            tooltip_date_time_format = "%x"
            [[[[observations]]]]
                [[[[[temp_min_max_avg]]]]]
                [[[[[tempdew]]]]]
                [[[[[outHumidity]]]]]
                [[[[[barometer]]]]]
                [[[[[windchill_heatindex]]]]]
                [[[[[wind]]]]]
                [[[[[windDir]]]]]
                [[[[[windRose]]]]]
                [[[[[rain]]]]]
                    aggregate_interval = 1555200  # 8 days
                [[[[[rainRate]]]]]
                [[[[[UV]]]]]
                [[[[[ET]]]]]
                    aggregate_interval = 1555200  # 8 days
                [[[[[radiation]]]]]
                [[[[[cloudbase]]]]]
                [[[[[appTemp]]]]]
                [[[[[climatogram_year]]]]]
                    bottom_date_time_format = "%b"
                    tooltip_date_time_format = "%B"


        [[[alltime]]]
            bottom_date_time_format = "%m/%y"
            tooltip_date_time_format = "%m/%Y"
            [[[[observations]]]]
                [[[[[temp_min_max_avg]]]]]
                [[[[[tempdew]]]]]
                [[[[[outHumidity]]]]]
                [[[[[barometer]]]]]
                [[[[[windchill_heatindex]]]]]
                [[[[[wind]]]]]
                [[[[[windDir]]]]]
                [[[[[windRose]]]]]
                [[[[[rain]]]]]
                [[[[[rainRate]]]]]
                [[[[[UV]]]]]
                [[[[[ET]]]]]
                [[[[[radiation]]]]]
                [[[[[cloudbase]]]]]
                [[[[[appTemp]]]]]
                [[[[[climatogram_statistics]]]]]
                    bottom_date_time_format = "%Y"
                    tooltip_date_time_format = "%Y"

        # Diagram heights.
        [[[heights]]]
            [[[[classic]]]]
                height = "220px"
                height_md = "300px"
                height_lg = "250px"
                height_xlg = "225px"
                height_max = "225px"
            [[[[alternative]]]]
                height = "220px"
                height_md = "325px"
                height_lg = "325px"
                height_xlg = "250px"
                height_max = "250px"

[CheetahGenerator]
    encoding = html_entities
    search_list_extensions = user.weewx_wdc.WdcGeneralUtil, user.weewx_wdc.WdcStatsUtil, user.weewx_wdc.WdcDiagramUtil, user.weewx_wdc.WdcCelestialUtil, user.weewx_wdc.WdcArchiveUtil, user.weewx_wdc.WdcTableUtil, user.weewx_wdc.WdcForecastUtil, user.weewx_wdc.RainTags

    #[[SummaryByDay]]
    #    [[[summary_day]]]
    #        template = day-archive/day-%Y-%m-%d.html.tmpl

    [[SummaryByMonth]]
        # Reports that summarize "by month"
        [[[NOAA_month]]]
            encoding = normalized_ascii
            template = NOAA/NOAA-%Y-%m.txt.tmpl
            #stale_age = 3600 # Every hour
        [[[summary_month]]]
            template = month-%Y-%m.html.tmpl
            #stale_age = 3600 # Every hour

    [[SummaryByYear]]
        # Reports that summarize "by year"
        [[[NOAA_year]]]
            encoding = normalized_ascii
            template = NOAA/NOAA-%Y.txt.tmpl
            #stale_age = 3600 # Every hour
        [[[summary_year]]]
            template = year-%Y.html.tmpl
            #stale_age = 3600 # Every hour

    # Reports that show statistics "to date", such as day-to-date,
    # week-to-date, month-to-date, etc.
    [[ToDate]]
        [[[day]]]
            template = index.html.tmpl

        #[[[yesterday]]]
        #    template = yesterday.html.tmpl

        [[[week]]]
            template = week.html.tmpl

        [[[month]]]
            template = month.html.tmpl

        [[[year]]]
            template = year.html.tmpl
            #stale_age = 3600 # Every hour

        [[[statistics]]]
            template = statistics.html.tmpl
            stale_age = 43200 # Twice a day

        [[[celestial]]]
            template = celestial.html.tmpl

        #[[[sensor_status]]]
        #    template = sensor-status.html.tmpl

        #[[[computer_monitor]]]
        #    template = computer-monitor.html.tmpl

    # Static pages, add as many as you want.
    [[Static]]
        [[[about]]]
            template = about.html.tmpl
            title = About
        #[[[externals]]]
            #template = externals.html.tmpl
            #title = Webcams/Externals
        #[[[DWD]]]
            #template = dwd.html.tmpl
            #title = Vorhersage vom DWD

[Units]
    [[TimeFormats]]
        # @see https://weewx.com/docs/customizing.htm#Units_TimeFormats
        day        = %X
        week       = %x
        month      = %x
        year       = %x
        rainyear   = %x
        current    = %x %X
        ephem_day  = %X
        ephem_year = %x
        stats      = %x %X
        daily_archive = %Y-%m-%d

[CopyGenerator]
    copy_once = dist/main.js, dist/main.css, plotly-custom-build.min.js, dist/live-updates.js, favicon.ico, manifest.json, icon-192x192.png, icon-256x256.png, icon-384x384.png, icon-512x512.png, service-worker.js, offline.html, dist/assets
    # copy_always =

[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator

**Comment by Supergamerx3000** [comment]
and here are my weewx_wdc section in weewx.conf

    [[WdcReport]]
        skin = weewx-wdc
        enable = true
        [[[Extras]]]
            radar_img = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
            radar_url = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
        [[[CheetahGenerator]]]
            search_list_extensions = user.weewx_wdc.WdcGeneralUtil, user.weewx_wdc.WdcStatsUtil, user.weewx_wdc.WdcDiagramUtil, user.weewx_wdc.WdcCelestialUtil, user.weewx_wdc.WdcArchiveUtil, user.weewx_wdc.WdcTableUtil, user.weewx_wdc_forecast.WdcForecastUtil, user.forecast.ForecastVariables
        [[[yesterday]]]
            template = yesterday.html.tmpl

**Comment by Daveiano** [comment]
Please remove the line 

`search_list_extensions = user.weewx_wdc.WdcGeneralUtil, ...`

from your **weewx.conf**. This seems like an old version of the Search List Extensions (before 3.x). It is also not needed anymore to add something to the search_list_extensions config for activating forecast (see the updated [wiki](https://github.com/Daveiano/weewx-wdc/wiki/Support-for-weewx-forecast)).

BTW: I think it should be:

```
[[WdcReport]]
    skin = weewx-wdc
    enable = true
    [[[Extras]]]
        radar_img = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
        radar_url = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
    [[[CheetahGenerator]]]
        [[[[ToDate]]]]
            [[[[[yesterday]]]]]
                template = yesterday.html.tmpl
```

**Comment by Supergamerx3000** [comment]
it works, the weather page is back, only the data from yesterday evening 10 p.m. until now are gone, but it doesn’t matter. Only the yesterday page does not appear yet? could it be because the data from yesterday is incomplete? I thank you for the help

**Comment by Daveiano** [comment]
Did you change the section in weewx.conf like I described in my previous comment? It's missing `ToDate` (Before yesterday).

**Comment by Supergamerx3000** [comment]
yes: 

    [[WdcReport]]
        skin = weewx-wdc
        enable = true
        [[[Extras]]]
            radar_img = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
            radar_url = https://www.dwd.de/DWD/wetter/radar/radfilm_hes_akt.gif
        [[[CheetahGenerator]]]
            [[[[ToDate]]]]
                [[[[yesterday]]]]
                  template = yesterday.html.tmpl

   which also surprises me that he does not load the radar image

**Comment by Daveiano** [comment]
It should be `[[[[[yesterday]]]]]` (5 square brackets), not `[[[[yesterday]]]]`. Every new section has one more bracket.

> which also surprises me that he does not load the radar image

Because its not `radar_img` and `radar_url` anymore. It´s `radar_html`: https://github.com/Daveiano/weewx-wdc/wiki/Configuration#extras. This was changed in [v3.0.0](https://github.com/Daveiano/weewx-wdc/releases/tag/v3.0.0)

**Comment by Daveiano** [comment]
@Supergamerx3000 Did this resolve your issue?
