### ISSUE TITLE
[BUG] links on the page ignore the dirctory

### ISSUE THREAD

**Issue by JDJoe** [Daveiano/weewx-wdc#161]
Install was fine. Original skins I have used also work fine. 
My weewx pages are served from webaddress:port/weewx directory but all links on your skin are pointing to / (root) and directory is ignored.

**Comment by JDJoe** [comment]
Got it working. 
It's not a bug.  Editing 2 separate files to get this stuff into proper directory is all it took.

**Comment by Daveiano** [comment]
> Got it working. It's not a bug. Editing 2 separate files to get this stuff into proper directory is all it took.

What do you mean by Editing 2 separate files?

You just need to set `basePath = /weewx/` in skin.conf.

See https://github.com/Daveiano/weewx-wdc/wiki#faq or https://github.com/Daveiano/weewx-wdc/wiki/WeeWX-related#setting-html_root-and-basepath or https://github.com/Daveiano/weewx-wdc/wiki/Configuration#extras

**Comment by JDJoe** [comment]
I decided to keep it out of weewx directory so it's shows up in /wdc
```
[StdReport]
    [[WdcReport]]
        skin = weewx-wdc
        enable = true
        HTML_ROOT = /var/www/html/wdc

```
in weewx.conf 

and base_path = /wdc/  in skins.conf

**Comment by Daveiano** [comment]
Ok, I assume it is now working for you? Glad you could solve it by yourself. I will close this issue for now, feel free to open a new one if you got any problems!
