### ISSUE TITLE
Add `color_dark` to diagrams config to allow explicitly set chart colors in dark mode

### ISSUE THREAD

**Issue by JDJoe** [Daveiano/weewx-wdc#163]
skin.conf 

```
    [[diagrams]]
.... 
                        observation = "extraTemp3"
                        color = "#e69138"
```
Has no effect on the line colour on the chart. 

added same colour code to         # Observation specific settings. block.
Same result. Not change. Line is white.

**Comment by Daveiano** [comment]
Ok, some more Info needed here. 

This could be either:

a) a real bug
b) Are you viewing the page using dark mode? If so, does your defined color showing up when switching to light mode? There is a logic implemented in dark mode, which checks if the color contrast between the dark background and the color of the chart line has a good enough color contrast. If not. the color is lightened up in dark mode, perhaps thats the case here?

**Comment by JDJoe** [comment]
> There is a logic implemented in dark mode, which checks if the color contrast between the dark background and the color of the chart line has a good enough color contrast.

WTF!? LOL. Why!? 
Colours do show up on light mode and would look perfectly fine on dark mode. 
It's not for the code (coder) to decide what colours I can or can not use.  How can I deactivate this "feature"? 

Edit: Here is what gets hidden by "logic" you mentioned: #ffc000 
Obviously, this logic is utterly flawed. :)

**Comment by JDJoe** [comment]
I took colour codes from diagrams that work. 
The result is no different - white lines in dark mode, coloured in light mode. 

I guess the problem is somewhere else.

**Comment by Daveiano** [comment]
> WTF!? LOL. Why!? 

Because a lot of the colours won't look good on the dark background in dark mode, and that's the best case. A dark red line of the line chart is badly seen on the background in dark mode. Because of that, the skin lightens colours up in dark mode to make them better visible. The feature evolved from a request of a color-blind person.

> Colours do show up on light mode and would look perfectly fine on dark mode.

No, like I said because of the above reasons.

> It's not for the code (coder) to decide what colours I can or can not use. How can I deactivate this "feature"?

Sorry, that's currently not possible. I would propose making it possible for the user to override this behaviour by defining a second config line like this: 

```
[[diagrams]]
    .... 
    observation = "extraTemp3"
    color = "#e69138"
    color_dark = "#e69138"
```

What do you think about that?

**Comment by JDJoe** [comment]
Where did this color_dark come from?

> We couldn’t find any code matching 'color_dark' in [Daveiano/weewx-wdc](https://github.com/Daveiano/weewx-wdc)


> 
>     Colours do show up on light mode and would look perfectly fine on dark mode.
> 
> No, like I said because of the above reasons.

#ffc000 looks fine. Your code is flawed.

**Comment by JDJoe** [comment]
color = "#ffc000"
color = "#92b6f0"

I tested this on 3 browsers - Firefox, Chromium and Brave - on desktop and also Firefox in Android. 
Only one showing coloured line for extraTemp2 and extraTemp3 is mobile phone. 

Maybe your style sheets are screwed or that CCP style "logic" thing has gone off the rails.

**Comment by Daveiano** [comment]
> Where did this color_dark come from?

I just proposed it, it is not yet implemented into the skin.
