### ISSUE TITLE
[BUG] Minor Spelling Error on Some Tiles

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#168]
**Describe the bug**
Rain, ET, and Wind Run use Totals instead of Total.
**To Reproduce**
1. Go to Main Page
2. See error

**Expected behavior**
Just Total on these tiles.

**Comment by Daveiano** [comment]
Thank you for spotting this! Sorry, I am not a native English speaker... 

I assume it should also be "Weekly total" instead of "Weekly totals", "Monthly total" instead of "Monthly totals" and so on?

**Comment by gary-hammer** [comment]
That is correct.
As I said, small thing.

**Comment by Daveiano** [comment]
Thanks for spotting this! I changed the translation file for en. This will be included in the next release.

If you want to change it right now, here are the needed changes (in `skins/weewx-wdc/lang/en.conf`): https://github.com/Daveiano/weewx-wdc/commit/ffb22b026143b1879c93d97751809b734100491d#diff-2c608082b550dc4abd44b8989b6bcaff80c214e1b60cc653396c7ec61a4e4156

**Comment by gary-hammer** [comment]
Thanks, going to able to test the combined rain tile this afternoon as well.
