### ISSUE TITLE
[BUG] Some graphs have undefined time value after update to latest skin 3.2

### ISSUE THREAD

**Issue by endmarsfr** [Daveiano/weewx-wdc#172]
**Describe the bug**
WeeWX version: 4.10.2 with MQTTSubscribeDriver
Skin: Weather Data Center 3.2.0

After updating to 3.2 skin version, 
some graphs have undefined value for time like "Inside Temperature"
![Weewx-wdc-3 2](https://github.com/Daveiano/weewx-wdc/assets/21008405/bfdc3813-09a0-4bdd-8de0-d426572f5583)

Here is my updated skin.conf
[skin.conf.txt](https://github.com/Daveiano/weewx-wdc/files/11576978/skin.conf.txt)

**Comment by endmarsfr** [comment]
I have the same behavior "undefined" time in graphs with extraTemp1 to extraTemp5

**Comment by Daveiano** [comment]
@endmarsfr That's not your actual skin.conf!?

In the screenshot, I see the classic layout, in the skin.conf you posted it says alternative layout?

Is your site anywhere publicly available so I could have a look at what gets generated by myself?

**Comment by Daveiano** [comment]
Never mind my last comment, I found the bug. 

Could you please edit the `weewx_wdc.py` file to test it? It's in the User directory (see https://weewx.com/docs/usersguide.htm#Where_to_find_things. If you installed WeeWX via setup.py it's at `/home/weewx/bin/user/weewx_wdc.py`)

At Line 1440, please replace

```
else:
    return diagram_base_props
```

with:

```
else:
    return {
        **diagram_base_props,
        **diagram_context_props
    }
```

This should fix the issue.

**Comment by endmarsfr** [comment]
Nice its solved :)
thank you very much
regards

**Comment by Daveiano** [comment]
Great! Thank you for testing this out. The fix will be included in the next release.
