### ISSUE TITLE
[BUG] Wind Speed Direction and Wind Gust Direction are Equal/Change At Same Time

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#177]
**Describe the bug**
I see the wind direction and the gust direction both change at the same time. 
This shouldn't be.

**To Reproduce**
1. View skin with MQTT enabled
2. Observe the two direction indicators
3. See error

**Expected behavior**
Direction of the current wind and the gust should be independent.

**Comment by Daveiano** [comment]
You are right, good catch! In MQTT `windDir` is used for both, `windSpeed` and `windGust`. I will have a look at it!

**Comment by Daveiano** [comment]
@gary-hammer I just noticed that my station only sends `windDir`, but not `windGustDir` (the hardware simply does not support it). What do you think would be the best approach for this? Using `windDir` also for the gust, or not updating the gust direction at all?

**Comment by gary-hammer** [comment]
I'm attaching the MQTT output from two different loggers of the same Davis PWS.
One the WiFiLogger2 and one the Davis WLL.

Both do have the direction for current and gust.
Perhaps an if would handle it? Else, you'd need to drop the gust direction indicator I'd think. It's not accurate as it stands.
[Davis-mqtt-info.txt](https://github.com/Daveiano/weewx-wdc/files/11715124/Davis-mqtt-info.txt)

**Comment by Daveiano** [comment]
> Else, you'd need to drop the gust direction indicator I'd think. It's not accurate as it stands.

Yes, that sounds reasonable! This will be available with the next update. I also fixed a bug when the initial page was rendered with 0 km/h wind speed, in that case the direction would never be shown. 

I attached a updated file (live-updates.js). Would be great if you could test this out (just replace the file in your skins directory at weewx/skins/weewx-wdc/dist/live-updates.js)

[live-updates.zip](https://github.com/Daveiano/weewx-wdc/files/11729198/live-updates.zip)

**Comment by gary-hammer** [comment]
I have replaced the file and run wee_reports

I did notice this the other day. I run Fully Kiosk Browser on the tablet to display your skin without browser navigation bars.
As today's max does not reset at midnight, I reopen the page when I wake everyday. That time of day is normally calm, so it will be easy to determine it's working with the new file.

I'll update you tomorrow.

**Comment by gary-hammer** [comment]
I see the gust and the current directions are now different.

**Comment by Daveiano** [comment]
> I did notice this the other day. I run Fully Kiosk Browser on the tablet to display your skin without browser navigation bars.
As today's max does not reset at midnight, I reopen the page when I wake everyday. That time of day is normally calm, so it will be easy to determine it's working with the new file.

Sorry for the fix with the "0 km/h wind speed" You will also have to change the stat-tile template (if you are using the alternative layout - or the conditions-table template if you are using the classic layout). The changes are here:  [#250b3c3](https://github.com/Daveiano/weewx-wdc/commit/250b3c3c2d6672cec8523453306daa94317a9a4f)

[stat-tile.inc](https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/includes/stat-tile.inc) - [download file](https://raw.githubusercontent.com/Daveiano/weewx-wdc/3.x/skins/weewx-wdc/includes/stat-tile.inc)
[conditions-table.inc](https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/includes/conditions-table.inc)  - [download file](https://raw.githubusercontent.com/Daveiano/weewx-wdc/3.x/skins/weewx-wdc/includes/conditions-table.inc)

Btw: you can also set `refresh_interval` to update the page once a day or something.

**Comment by gary-hammer** [comment]
Done. The file opened in my browser vs download, but I pasted all into a text editor, changed to *nix file terminators, and uploaded to my server.

I'll need to reload in the AM to know for certain.

Not a problem to manually reload it in the morning when get coffee. I'm just not a big fan of webpages that reload on a schedule. I guess I can have FKB do this for me though. The free version does an enormous amount of tasks, paid is mostly for business use like a display or some such.

https://www.fully-kiosk.com/en/#features

**Comment by gary-hammer** [comment]
Working as intended.
Luckily when I opened the page it was calm.
2 screenshots attached.

If you are happy with the results, feel free to close this ticket.
![calm](https://github.com/Daveiano/weewx-wdc/assets/12861605/61fe669a-ab04-47d5-9695-2eafea87969a)
![wind](https://github.com/Daveiano/weewx-wdc/assets/12861605/e028c406-0b29-483f-bb15-cc2fc8b585c4)

**Comment by Daveiano** [comment]
Great, looks good! As I said, will be included in the next release!
