### ISSUE TITLE
[BUG] most_days_with_rain and last_rain not found

### ISSUE THREAD

**Issue by endmarsfr** [Daveiano/weewx-wdc#183]
Hello,
I installed latest weewx-wdc version 3.3.0

```
WeeWX uptime: 0 days, 0 hours, 5 minutes
Server uptime: 3 days, 19 hours, 53 minutes
WeeWX version: 4.10.2 with MQTTSubscribeDriver
Skin: Weather Data Center 3.3.0
```
`wee_extension --uninstall=weewx-wdc`
`rm -rf /var/www/weewx/*`
...
installation guide of the new 3.3.0 plugin
...
`wee_reports`

But unfortunatelly, i had an error in weewx log :
`juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/year-%Y.html.tmpl failed.
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/year-%Y.html.tmpl
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'most_days_with_rain'
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/year-%Y.html.tmpl failed.
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/year-%Y.html.tmpl
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'most_days_with_rain'
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
juil. 09 15:22:32 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/year-%Y.html.tmpl failed.
...
juil. 09 15:23:10 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/statistics.html.tmpl failed.
juil. 09 15:23:10 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/statistics.html.tmpl
juil. 09 15:23:10 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'last_rain'
juil. 09 15:23:10 radio weewxd[75101]: weewx[75101] ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template`

I submit my weewx.conf and skin.conf  files renamed with .txt extension :
[weewx.conf.txt](https://github.com/Daveiano/weewx-wdc/files/11995278/weewx.conf.txt)
[skin.conf.txt](https://github.com/Daveiano/weewx-wdc/files/11995279/skin.conf.txt)

of course, statistics and year-xxx models don't work.

I also have empty pages on sensor status and computer screen.

tell me, if you need more elements

regards

**Comment by Daveiano** [comment]
In your skin.conf: you are missing a new search_list_extension added in the last update (`user.weewx_wdc.RainTags`):

`[CheetahGenerator]search_list_extensions` should be `user.weewx_wdc.WdcGeneralUtil, user.weewx_wdc.WdcStatsUtil, user.weewx_wdc.WdcDiagramUtil, user.weewx_wdc.WdcCelestialUtil, user.weewx_wdc.WdcArchiveUtil, user.weewx_wdc.WdcTableUtil, user.weewx_wdc.WdcForecastUtil, user.weewx_wdc.RainTags`

See https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/skin.conf#L562C30-L562C269

**Comment by Daveiano** [comment]
**Computer status page**: Do you actually have [weewx-cmon](https://github.com/matthewwall/weewx-cmon) installed? Did you have a look at the [wiki](https://github.com/Daveiano/weewx-wdc/wiki/Support-for-weewx-cmon) page for setting it up? 

**Sensor status page**: There is also a wiki page for that: https://github.com/Daveiano/weewx-wdc/wiki/Sensor-Status-Page
What observations does your station provide? Perhaps you need to update the `sensor_stat_*` configs in skin.conf?

**Comment by endmarsfr** [comment]
Thank you. It works now 

I'am trying to put all my custom settings from skin.conf to weewx.conf to avoid errors in next skin's updates.
But some settings not works if I move them to weewx.conf.

For instance, if I move in WDCReport, Extras section, the following setting, that not work, it always take Skin.conf settings. If I comment it in skin.conf, there is an error :

    [[forecast_table_settings]]
        source = OWM
        num_periods = 72
        num_days = 5
        show_hourly = 1
        show_day = 1
        show_date = 1
        show_outlook = 1
        show_temp = 1
        show_dewpoint = 0
        show_humidity = 0
        show_wind = 1
        show_tides = 0
        show_sun = 1
        show_moon = 1
        show_pop = 1
        show_precip = 1


Is there a list of settings than can be moved from skin.conf to weewx.conf ?

Kind Regards

**Comment by Daveiano** [comment]
It should work with every config. Are you sure you are using it as following in `weewx.conf`?

```ini
[StdReport]
    [[WdcReport]]
        skin = weewx-wdc
        enable = true
	lang = fr
        [[[Extras]]]
            [[[[forecast_table_settings]]]]
                source = OWM
                num_periods = 72
                num_days = 5
                show_hourly = 1
                show_day = 1
                show_date = 1
                show_outlook = 1
                show_temp = 1
                show_dewpoint = 0
                show_humidity = 0
                show_wind = 1
                show_tides = 0
                show_sun = 1
                show_moon = 1
                show_pop = 1
                show_precip = 1
```

The correct number of brackets is important here (Four brackets in `[[[[forecast_table_settings]]]]`).

**Comment by endmarsfr** [comment]
Thank, it worked for OWM.
So, i tried to move all my custom settings from skin.conf to weewx.conf
But I had a different behavior for diagrams
With the following shared file weewx.conf, and the standard skin.conf  I expected to have "temp_min_max_avg" and "appTemp" diagram in first, but it was not.
It's seem's I had a mix of Skin.conf & weewx.conf settings as you can see in the shared picture.
skin.conf is the latest v3.3.0 one, this the current one I used.
Weewx.conf is my current weewx settings
and 
skinBackup.conf was my previous customized settings, that had the expected behavior.

I can't find where I went wrong :(

![radio local_weewx_index html](https://github.com/Daveiano/weewx-wdc/assets/21008405/3c0b40f4-e394-4435-ab36-3c40289f8c71)
[skinBackup.conf.txt](https://github.com/Daveiano/weewx-wdc/files/12042496/skinBackup.conf.txt)
[skin.conf.txt](https://github.com/Daveiano/weewx-wdc/files/12042497/skin.conf.txt)
[weewx.conf.txt](https://github.com/Daveiano/weewx-wdc/files/12042498/weewx.conf.txt)

**Comment by Daveiano** [comment]
Oh yes, you are right! I was not aware of that. WeeWX merges the configs together, resulting in options like the diagrams to be "added up" (skin.conf + weewx.conf). You can read about the mechanics here: https://www.weewx.com/docs/latest/customizing.htm#Processing_order

So if you want to change the diagrams (especially if you want to remove diagrams from the display), you must do it in skin.conf.

**Comment by endmarsfr** [comment]
Thanks a lot.
I observed a new behavior with the new skin v3.3.0.
I a value is NA, it is not showed in the tiles
Is this new behavior could be controled by a setting in skin.conf ?

**Comment by Daveiano** [comment]
Where have you observed this? In the table or for the charts, or for both?

There were some changes regarding this in v3.3.0, but it should work like before: If an observation has not any data for the observations time span (day, week, etc) it won't be shown. Why would you want to change this behaviour? Could you please give some context?

**Comment by endmarsfr** [comment]
First of all, thank you again for your interest and your investigations.

I noticed the change on the tiles.
I use several data sources for my weewx site.
1 - an SDR receiver to process data received by radio
2 - From my bresser station which I capture via wifi.
Sometimes the data is not captured during the capture interval.

In versions 3.2.0 and earlier, I had NA values when data could not be received.  In the tiles, the NA value was displayed along with the day's min and max values for the capture interval where the value is missing.
Now, with version 3.3.0, when a value is NA, it is no longer displayed in the tiles.
I was wondering if there was now a parameter that managed the display of NA values in tiles? 

I hope my question is now clearer

Kind regards

**Comment by Daveiano** [comment]
Ah ok, I understood. You are right, this changed since the last version: The condition is now `if $current.obs.has_data`, instead of `$day.obs.has_data`. To be honest, I thought it would be better to check against `$current`, but you are right. Since the min/max value of the day is shown, it absolutely makes sense to check against `$day` to determine if the observations should be shown. 

I don't think it makes sense to make this configurable since it definitely should use $day in that case, or what do you think?

Note to myself: https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/includes/conditions-table.inc#L66 and https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/includes/body-alternative.inc#L74

**Comment by endmarsfr** [comment]
Hello,

Sorry for the delay in my reply.

I think that if the "show_min_max_time_day" option is set to True, it is mandatory to display the values even if they are NA. Indeed, with the current behavior, the min/max values are lost.

But if the "show_min_max_time_day" option is set to false, it might be more useful to hide the NA values.

But if these rules can't be applied, I prefer to revert to the previous behavior and use: "$day.obs.has_data" in the templates.

With kindest regards

**Comment by Daveiano** [comment]
> I think that if the "show_min_max_time_day" option is set to True, it is mandatory to display the values even if they are NA. Indeed, with the current behavior, the min/max values are lost.

>But if the "show_min_max_time_day" option is set to false, it might be more useful to hide the NA values.

This sounds like a good solution! I created #188 for this, the change will be included in the next release!

I will close this issue because the original problem was already solved. Feel free to open another issue or a new discussion if you have general configuration questions. Thank you for your input!
