### ISSUE TITLE
[BUG] base_path missing for NOAA Report HREF

### ISSUE THREAD

**Issue by endmarsfr** [Daveiano/weewx-wdc#184]
Hello,
I installed latest weewx-wdc version 3.3.0

```
WeeWX uptime: 0 days, 0 hours, 5 minutes
Server uptime: 3 days, 19 hours, 53 minutes
WeeWX version: 4.10.2 with MQTTSubscribeDriver
Skin: Weather Data Center 3.3.0
```
```
wee_extension --uninstall=weewx-wdc
rm -rf /var/www/weewx/*
...
installation guide of the new 3.3.0 plugin
...
wee_reports
```

But unfortunatelly, i had an error when I tried to view NOAA Report, as you can see it, base_path is missing in NOAA Report HREF.
![NOAAReport](https://github.com/Daveiano/weewx-wdc/assets/21008405/43c3a87f-76ed-473d-892a-45e62b286b06)
My base_path is /weewx, in weewx.conf

If I change, http://radio.local/NOAA/NOAA-2021-01.txt to http://radio.local/weewx/NOAA/NOAA-2021-01.txt in my browser, I can see NOAA Report.

In Template "month-%Y-%m.html.tmpl"
href="NOAA/NOAA-${month.start.format('%Y-%m')}.txt" should be prefixed with base_path.

Regards

**Comment by Daveiano** [comment]
Oh yes, you are right, good spot!

I made the needed changes in [7bcedf4](https://github.com/Daveiano/weewx-wdc/commit/7bcedf48352a513f318d4ebea95807049e85ac2d). Feel free to test this out if you feel familiar with editing the template files - feel free to ask if you need help on this.

The fix will be included in the next release!

**Comment by endmarsfr** [comment]
Hello
Thank you for the fix.
It works well

Kind Regards
