### ISSUE TITLE
Add an option to configure number of columns for the Current Weather Conditions etc page

### ISSUE THREAD

**Issue by JDJoe** [Daveiano/weewx-wdc#186]
Add an option to configure number of columns for the "Current Weather Conditions" . Currently, I have to open a browser window and make it really narrow so the 
```
Outside Temperature        Outside Humidity
Temperature 1              Humidity 1 
UV Index                   Radiation
etc...


```
line up side by side and in pairs.

**Comment by Daveiano** [comment]
I guess you want to change the number of columns for the charts, right? Are you using the classic or alternative layout? Just asking because the classic layout already shows 2 columns of charts on big screens.

**Comment by JDJoe** [comment]
> Are you using the classic or alternative layout? 
I have no idea. What ever the default is. 

>  classic layout already shows 2 columns of charts

Charts? Was I talking about charts? No! I am not talking about charts.  I am talking about the f'n "Current Weather Conditions" block that has dynamic width and has "Outside Temperature ", "Outside Humidity" etc **text** boxes. 

I even made you a f'n ASCI art example... LOL.
