### ISSUE TITLE
webcam not working

### ISSUE THREAD

**Issue by wifi75** [Daveiano/weewx-wdc#189]
Hello I'm trying the webcam that works with the following link from my browser, but it doesn't work in the skyn.
what am I doing wrong?

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/3459ed4d-08c6-4551-ab5b-6265a98d3082)

**Comment by Daveiano** [comment]
I don't think you can use Basic Authentication inside HTML image sources. Chrome for example blocks these requests, see https://chromestatus.com/feature/5669008342777856

You should make your webcam images accessible without authentication needed. Sorry, but this has nothing to do with the skin.

**Comment by Daveiano** [comment]
@wifi75 I consider this issue as closed. Please feel free to open a discussion if you need help regarding this!
