### ISSUE TITLE
Tool Tip out of Scope

### ISSUE THREAD

**Issue by gand07** [Daveiano/weewx-wdc#194]
If the measurement on the graph is off to the right, the Tool Tip cannot be read. 

Is it possible to move the Tool Tip to the left of the cursor so that it can be read?

The graph Windchill/Heatindex the Tool Tip seems to be left of the cursor and can be read

Rgds
Gert
![Tool Tip](https://github.com/Daveiano/weewx-wdc/assets/47734099/88eb00d6-32e4-4db7-bf69-50040c409f30)

**Comment by Daveiano** [comment]
Yes, you are right, the tooltip should not be cut off here, good catch!

This seems to only happen for bar charts it seems. I will have a look and include a fix in the next release!
