### ISSUE TITLE
Different Time Formats

### ISSUE THREAD

**Issue by gand07** [Daveiano/weewx-wdc#195]
Hi
Where can I change the Tool Tip date format. As you can see from the screenshot, the Tool Tip shows AM/PM, the X-axis shows the 24-hour date format (which I want). Also the current weather conditions is right.

Thanks
Gert
![Date](https://github.com/Daveiano/weewx-wdc/assets/47734099/90667a34-48ad-4851-9a37-ff023b5fc40d)

**Comment by Daveiano** [comment]
Please have a look at https://github.com/Daveiano/weewx-wdc/wiki/Configuration#configuring-date-and-time-formats

You can configure this per chart or per observation.

**Comment by gand07** [comment]
Sorry did’t see that. Solved 
Gert
