### ISSUE TITLE
Enhancement to the All Time Statistics

### ISSUE THREAD

**Issue by gand07** [Daveiano/weewx-wdc#196]
Could it be an idea to have the All Time separated into years. When I go with WDC, I have 10 years of data and then I can see I have 500 Rains Days during the 10 years, maybe no so useful. If separated, it's possible to do wear to year comparison 
The table should include(as now):

Rain days	
Summer days
Hot days	
Desert day	
Tropical Night	
Storm Days
Ice Days	
Frost days
Total number of days

See attachment.

Rgds
Gert
[Enhancement.pdf](https://github.com/Daveiano/weewx-wdc/files/12385360/Enhancement.pdf)

**Comment by Daveiano** [comment]
You can always go to the specific year or month archive pages (links in the sidebar) to get stats per year or month.

But yes, I guess a table with all information at a glance would be a good addition! Also that the data is displayed per month would be a great feature to see detailed information.

I will think about this a bit and post a proposal implementation. Thank you for your input!

**Comment by Daveiano** [comment]
@gand07 I got some time to work on this is how it looks like:

![196](https://github.com/Daveiano/weewx-wdc/assets/3184897/e27021aa-8550-4fbe-934c-b3e03fd7486c)

I also added an additional row to show the average days per month, I guess this could also be useful. On top of the table, there are tabs to switch between Rain days, Summer days, etc.

What do you think?

**Comment by gand07** [comment]
Hi
That’s looking very good and very useful. Now you have all the information in 1 table and can compare year by year. Very good and thanks for that.
Also thank you for the scrollable sidebar and the placing the tooltip so it can be read.
Gert

**Comment by Daveiano** [comment]
Great! Then this will be included in the next release.

No problem, I am always happy to help and to improve the skin!
