### ISSUE TITLE
Wind and Gust speed have a space between unit and comma

### ISSUE THREAD

**Issue by caphector** [Daveiano/weewx-wdc#200]
**Describe the bug**
The wind speed values have a space between the unit and the comma. Also, `Today's` should have an apostrophe

```
Todays Max
13 mph , N
```

**Expected behavior**
There should not be a space there

**Screenshots**
<img width="192" alt="image" src="https://github.com/Daveiano/weewx-wdc/assets/8420750/d3d527c3-08d4-42d7-8aa7-7cd9962f5fee">

**Additional context**
I believe this is because the HTML has a line break between the <spans>
```
<p class="stat-value">
 <span class="value" style="display: inline;">13 mph</span>
 <span class="stat-wind-dir stat-detail">, N</span>
</p>
```

Thanks for the skin; I like having it on my site.

**Comment by Daveiano** [comment]
Hello there and thanks for reaching out!

You are right, there is an additional space, I will have a look at this. Sorry I am no native English speaker, so I did not notice the missing apostrophe. 

Fixes will be available in the next 3.4.0 release, please be patient.
