### ISSUE TITLE
Per Month Tables

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#215]
Provide per-month tables: E.g. for `outTemp`: Temperature per month (probably with min/max), like in GH-196

- Configurable? Set which observations should get a table, and use `stat_tiles_show_min/max/sum` to determine what to show
- Show on stats and year pages

| Year    | Jan   | Feb   | Mar    | ... | Average | Min | Max |
|---------|-------|-------|--------|-----|---------|-----|-----|
| 2021    | 3.4°C | 5.7°C | 10.1°C | ... | X°C     | X°C | X°C |
| 2022    | 4.5°C | 5.5°C | 8.2°C  | ... | X°C     | X°C | X°C |
| Average | X°C   | X°C   | X°C    | X°C | ?       | ?   | ?   |
| Min     | X°C   | X°C   | X°C    | X°C | ?       | ?   | ?   |
| Max     | X°C   | X°C   | X°C    | X°C | ?       | ?   | ?   |

The fuzzy-archer skin has also a very good implementation: https://kainzbauer.net/weather/Rif/history.html

**Comment by gand07** [comment]
Great idea
