### ISSUE TITLE
Opening Webcam Links/Stat Tile links in a Modal

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#220]
The clickable tiles work verry well!  Thank you for that.
But I have yet another  small feature request. Would it be possible to open the destination sites or HTML pages in the main I-frame of the skin in stead of in a full browser window?
![weewx-wdc](https://github.com/Daveiano/weewx-wdc/assets/36402924/82e1387f-553a-4a8d-93e6-e95c9f494ce4)

I mean the yellow part of the site in attached screenshot.

Again, thank you for your effort and the quick responses.
Regards,
Ed.

_Originally posted by @dystechnic in https://github.com/Daveiano/weewx-wdc/discussions/211#discussioncomment-7475861_

**Comment by Daveiano** [comment]
I created a new issue for that, because the discussion in #211 should be solved.

So this sounds like kind of a "Kiosk page"? 

To be clear: You want only the Gauges and Stat tiles to be shown on the page. Without Navigation and Header Bar, right? Should this only be for the main Index page, or all pages?

**Comment by dystechnic** [comment]
HI,

No,what I meant was that if you click on a tile the referred page opens in the same area as the gauges and tiles. In that frame.With the Header and navbar still visible. This would be usefull for the tile referrals as well for the webcam / skycam links.
That way you don't have to use the browser's back button to get back to the index page. The screen we use is already in kiosk mode, so without useable browser buttons. 

Regards,
Ed.

**Comment by Daveiano** [comment]
Ah ok, I got you!

> as well for the webcam / skycam links

You mean the links from the sidebar?

**Comment by dystechnic** [comment]
Yes, the links from the sidebar. But now I think of it, if the linked webcam sites of the images in the externals tile would open in that same frame would be als nice ;-)

**Comment by Daveiano** [comment]
Ok, I understand. Another user already had a similar idea, but with a Modal.

So the referenced stat tiles pages and/or webcam images are opening in a modal on top of the page. I personally think that's a better solution than replacing the content on the top of the page. What do you think about that approach?

**Comment by dystechnic** [comment]
I had to see what a modal was but that seems as a perfect solution.

**Comment by Daveiano** [comment]
Yeah something like an overlay which sits on top of the page and can be closed easily via a close button/icon, should also work well on a touch screen.

I will include this in the next feature release, but I don't know if I will be able to get this out within this year, could be probably finished in the early 2024.

**Comment by Daveiano** [comment]
Hi, I managed to get some time to implement this!

I released a pre-release, [v3.5.0-alpha1](https://github.com/Daveiano/weewx-wdc/releases/tag/v3.5.0-alpha1), for you to test this out. Please follow the normal [update instructions](https://github.com/Daveiano/weewx-wdc#updating-the-skin).

You can now set [`[Extras]open_radar_and_externals_modal`](https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/skin.conf#L38) and you can use the new option `open` for the stat tile links:

```config
[[stat_tile_links]]
    [[[ET]]]
        link = "https://en.wikipedia.org/wiki/Evapotranspiration"
        open = modal  # modal, new_tab or same_tab
```

**Comment by dystechnic** [comment]
Great, thank you.
I'm a bit busy at the moment but I will try it as soon as possible. I'll let you know the result.

**Comment by dystechnic** [comment]
Hi, I tried the alpha version today but the skin will not load.
I followed the update instructions and removed the old version, installed the alpha version and changed the skin.conf to suit my installation.
But The skin will not load. I'm stuck with the default Seasons skin.
wee_reports runs  without error and the weewx.service is also running without issue.

**Comment by Daveiano** [comment]
Could you provide the relevant section (or the whole file) of your weewx.conf?

Also the logs of a full report run would be useful.

**Comment by dystechnic** [comment]
Attached the complete weewx.conf and the log ofa full wee_report run.
[syslog.txt](https://github.com/Daveiano/weewx-wdc/files/13549685/syslog.txt)
[weewx.conf.txt](https://github.com/Daveiano/weewx-wdc/files/13549686/weewx.conf.txt)

**Comment by Daveiano** [comment]
The sylog tells that you are missing the `open` property:

```
Dec  4 18:44:01 weewx wee_reports[29681] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/year.html.tmpl failed with exception '<class 'KeyError'>'
Dec  4 18:44:01 weewx wee_reports[29681] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/year.html.tmpl
Dec  4 18:44:01 weewx wee_reports[29681] ERROR weewx.cheetahgenerator: **** Reason: 'open'
```

You should provide the `open` property to every linked stat tile like:

```
[[stat_tile_links]]
    [[[ET]]]
        link = "https://en.wikipedia.org/wiki/Evapotranspiration"
        open = modal  # modal, new_tab or same_tab
```

**Comment by dystechnic** [comment]
Thank you! It works now.
Stupid me. I assumed there was a default so I did not change that after the upgrade. 

It is not exactly what I meant. If I click on a link, the whole page, inclusive header and sidebar opens in a modal. In that modal you can go back to the homepage and again click on a link.That link opens in a modal. But now only the referred page opens. Without header and sidebar. I would expect this for the first modal.
In the attached imagethe red square is the first link to a modal page and the green the second(nested) link.
![modal](https://github.com/Daveiano/weewx-wdc/assets/36402924/fc3d3294-57a8-4cbf-ad9d-5aac9518fdb9)

**Comment by Daveiano** [comment]
While I understand what you want to do, I think this is out of scope for something the skin could do by itself. There is no reliable way to manipulate a website in frame in that way.

What you should do is hide the header and sidebar from your "explanation pages". I assume you created custom template files for your pages. Something like wolkenbasis.html.tmpl? 

To do this you can simply paste this snippet into your templates (best suited inside the `<head>` tags):

```html
<style>
  bx-header {display: none;}
  bx-side-nav {display: none;}
  main.bx--content {margin-top: 0; margin-left: 0 !important;}
  #footer {display: none;} /*This will also hide the footer*/
</style>
```

I hope this solves this? Sorry, I did not get this right until now.

**Comment by dystechnic** [comment]
Sorry for the late reaction but this addition to the templates doe the trick.
Thank you!

I have one other puzzle.Ho can I get the skin to be dark at all times? The default is light until you push the button. I would like to be it default dark so it is dark the first time you open it.
Should I make an other discussion or issue for this?

**Comment by Daveiano** [comment]
> Sorry for the late reaction but this addition to the templates doe the trick.

Glad to hear that! Then this will be included in the next release!

> I have one other puzzle.Ho can I get the skin to be dark at all times? The default is light until you push the button. I would like to be it default dark so it is dark the first time you open it.
Should I make an other discussion or issue for this?


Just to be clear: If you switch to dark mode - it should stay in dark mode until you change it again, also if you close and reopen the page (on the same device). Thats also the case for you, right?

I guess you want to change the default to dark and also hide the dark/light toggle? Yes, would be great if you could open another issue for that, just describe your needs in that ticket! Thank you very much for all the feedback!
