### ISSUE TITLE
Skin reverts to english after cheetagenerator runs [BUG]

### ISSUE THREAD

**Issue by dystechnic** [Daveiano/weewx-wdc#221]
**Describe the bug**
I use version 3.4.0 of the skin.
I use it with the nl translation and initially all is fine.The skin is in dutch as expected. But after a while the skin reverts back to en.  

**To Reproduce**
1. enable dutch in weewx.conf (lang = nl) and in skin.conf (date_time_locale = nl-NL). 
2. run wee_reports to generate the needed files.The skin is now in the correct language. (dutch) 
3. wait for cheetagenerator to run. I check with 'systemctl status weewx.service'. This runs about every 5 minuts.
4. refresh the page in your browser
5. the skin has reverted to english in my case.

**Expected behavior**
The skin stays in the expected language. Dutch in my case.

**Additional context**
Version 3.3.0 didnot have this issue. Don't know if this helps or not.

**Comment by dystechnic** [comment]
Some extra info:
16:41  run wee_reports     ==>   Skin in dutch

systemctl status weewx.service'
```
nov 05 16:45:15 weewx weewxd[21904]: weewx[21904] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.74 seconds
nov 05 16:45:15 weewx weewxd[21904]: weewx[21904] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.35 seconds
nov 05 16:45:15 weewx weewxd[21904]: weewx[21904] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html
nov 05 16:45:15 weewx weewxd[21904]: weewx[21904] INFO weewx.cheetahgenerator: Generated 12 files for report forecast in 0.08 seconds
nov 05 16:45:15 weewx weewxd[21904]: weewx[21904] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/forecast

```
As of this moment the skin is in english.

**Comment by Daveiano** [comment]
Can you please verify that the file `skins/weewx-wdc/lang/nl.conf` exists?

I forgot to include it in the "install script" (already fixed, see 091edd0), but I assume the file exists for you because you had copied it earlier. 

**However**, I can reproduce this behaviour, but only on my local test machine, when I change the language on my production machine, it stays the correct one and does not change. So I assume its a config mistake somewhere, I will do some more research...

**Comment by Daveiano** [comment]
I think I figured it out, after looking in my weewx directory, I saw a lot of weewx.conf.backup files:

![Screenshot from 2023-11-06 18-56-04](https://github.com/Daveiano/weewx-wdc/assets/3184897/44528a3a-f5aa-498e-93e5-ed2972ec3860)

After removing these with 

```
sudo rm weewx.conf.2022*
sudo rm weewx.conf.2023*
```

and restarting weewx, the language does not change anymore. Can you please have a look if it's the same problem for you?

**Comment by dystechnic** [comment]
Yes, removing the old log files did the trick. 
I don't understand why, but thank you for finding this solution.

**Comment by Daveiano** [comment]
> I don't understand why, but thank you for finding this solution.

Me neither but this is not related to the skin. The language is handled by WeeWX itself. I tested this and it is the same for the default Seasons Skin. You could post to https://groups.google.com/g/weewx-user/ if it bothers you.
