### ISSUE TITLE
MQTT connection with username/password

### ISSUE THREAD

**Issue by wifi75** [Daveiano/weewx-wdc#225]
Hello My weewx send data to  my mqt tserver,
my broker have usr and password.
as skyn.conf missing line for set mqtt user and password, 
in fact skyn does not connect to mqtt to collect the data and generate the gauge.

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/f869806a-fb1b-4230-83b9-f39474997d46)

this is my mqtt sky configurazion

 # For instructions, see https://github.com/Daveiano/weewx-wdc/wiki/Support-for-weewx-mqtt
    [[mqtt]]
        mqtt_websockets_enabled = 1
        mqtt_websockets_host = "192.168.1.52"
        mqtt_websockets_port = 1884
        mqtt_websockets_ssl = 0
        mqtt_websockets_topic = "weather/loop"

How should I add a user and password?

**Comment by Daveiano** [comment]
The skin currently only supports connecting anonymously to the MQTT broker, without a username and password. 

I was not aware of people using credentials on the client side, since they are exposed to the public. 

I will add this in the next release, please be patient!

**Comment by wifi75** [comment]
My Broker on Home assistant is configured with user name and password...
ok I will wait for the new version
Thank you

**Comment by wifi75** [comment]
hello, how I  Can try?

**Comment by Daveiano** [comment]
I released a pre-release, [v3.5.0-alpha1](https://github.com/Daveiano/weewx-wdc/releases/tag/v3.5.0-alpha1), for you to test this out. Please follow the normal [update instructions](https://github.com/Daveiano/weewx-wdc#updating-the-skin).

You can now set `mqtt_websockets_username` and `mqtt_websockets_password` in skin.conf, see https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/skin.conf#L45

**Comment by wifi75** [comment]
nathing, not working:

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/e4f879af-2abb-477e-abb6-422ef788ec9c)


my broker websocket work on port 1884:

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/6b99e290-ee5c-4b70-9de3-e1a359504612)

on mqtt explorer data it is ok:

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/06cfc0f5-c721-466f-8d3b-b4020cc810c1)

**Comment by Daveiano** [comment]
Ok, that's difficult for me without something to look at.

Some ideas:

- You are using a local IP, I assume the skin is hosted in that same network and has access to the specified IP?
- Do you have any idea which MQTT version you are using (MQTTv3.1.1 vs MQTTv3.1)
- In the Browser open the Console (via F12 for most browsers, more info here https://screenful.com/guide/how-to/how-to-open-the-browser-developer-console). In the console you should see an error message?

![274109325-d9603442-edcb-43bf-b385-b3a21584e9d6](https://github.com/Daveiano/weewx-wdc/assets/3184897/64a4f610-b8b9-4e63-bb31-c4e8421f3b8e)

What is the error saying?

**Comment by wifi75** [comment]
broker have static ip and my broker it is inatalled on Home assistant
https://github.com/home-assistant/addons/tree/master/mosquitto

below my console error
![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/c7bb9990-b5c5-4725-989f-e2886f36b405)

**Comment by Daveiano** [comment]
From the screenshot, it looks like you are using secure websockets via SSL (wss://...). Your home assistant config uses non-secure (ws://...) connection on port 1884.

So you should either use 

```
mqtt_websockets_port = 1884
mqtt_websockets_ssl = 0
```

or 

```
mqtt_websockets_port = 8884
mqtt_websockets_ssl = 1
```


> broker have static ip and my broker it is inatalled on Home assistantbroker have static ip and my broker it is inatalled on Home assistant

Please correct me if I am wrong but the skin has no access to 192.168.1.52! If I am accessing https://meteo.iu3cyv.eu/weewx/ I have no access to YOUR local IP. The only way this could work is when you are accessing the skin in the same network as your Home assistant is operating. 

Please let me know if this helps you, you should inform yourself about the differences between Local/Private IPs vs Public IP addresses.

**Comment by wifi75** [comment]
hello [Daveiano](https://github.com/Daveiano) nothing you wrote to me is correct,
broker mqtt and meteo weewx server they are on the same local network, weewx reaches the mqtt broker easily!
in the skin configuration I am using the non-secure websocket on port 1884, in fact I configured it like this:
mqtt_websockets_ssl = 0

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/860b7ef3-8621-4aae-8883-68a87fba6a0d)

witch this configuration my mqtt explore work !
![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/aa1a6a5c-0dd1-41fd-b705-ac527615aa60)

![image](https://github.com/Daveiano/weewx-wdc/assets/31816231/90c806d3-4bba-4e42-855f-0841582242ef)

**Comment by Daveiano** [comment]
First of all, I just re-configured my MQTT Broker to use a username & password for read access and it works. So the general implementation works.

> in the skin configuration I am using the non-secure websocket on port 1884, in fact I configured it like this:
mqtt_websockets_ssl = 0

Perhaps you configured something in weewx.conf (`[StdReport][[WdcReport]]`)? Configurations in weewx.conf have a higher priority than configs in skin.conf. The screenshot clearly proves that your page tries to connect via secure websockets (wss):

![GH-225](https://github.com/Daveiano/weewx-wdc/assets/3184897/a7b35e9f-4587-46dd-8c20-1456467cf40c)

> hello [Daveiano](https://github.com/Daveiano) nothing you wrote to me is correct,
broker mqtt and meteo weewx server they are on the same local network, weewx reaches the mqtt broker easily!

I think I was not clear about this: It's not weewx, which subscribes to the MQTT broker, it's the browser (the client). Again: If I visit https://meteo.iu3cyv.eu/weewx/, my Browser will have NO access to any of your local IPs. This will only work if you visit the page in the same network as your Broker lives.

**Comment by wifi75** [comment]
SOrry but what is th correct skin configuration for connect without ssl?

**Comment by Daveiano** [comment]
`mqtt_websockets_ssl = 0` should do it. Does it not work?

**Comment by wifi75** [comment]
> `mqtt_websockets_ssl = 0` should do it. Does it not work?

in my configuration, as you can see from the screenshots it is already at 0 but I don't understand why it connects to wss from the chrome console..
why do you think?

**Comment by Daveiano** [comment]
Could you please check if there are mqqt skin settings defined in weewx.conf? Like I said in a previous comment:

> Perhaps you configured something in weewx.conf ([StdReport][[WdcReport]])?

I did some research and found out that the MQTT Client first tries to connect via the specified protocol (without SSL) and if that fails it tries to connect the other option (with SSl in that case) - so it seems this is normal behaviour because the connection is failing.

Any news on the IPs? My simple guess is that your broker is not reachable by the MQTT Client (Browser).

**Comment by wifi75** [comment]
my broker can be reached by clients.
in weewx.conf I don't have any mqtt skin configuration.

However, I'm waiting for the new version of homeassistant which will be released at the beginning of December. it seems the current one doesn't accept mqtt websocket. We see....
I will keep you updated

**Comment by Daveiano** [comment]
Ok, good news! Thank you!

**Comment by Daveiano** [comment]
@wifi75 Any news on this? 

I would like to close this issue. Auth via username/password is included and I don't see any way I can support you further on this.
