### ISSUE TITLE
[BUG??] Lots of errors after upgradin to 3.4.0

### ISSUE THREAD

**Issue by iiseppi** [Daveiano/weewx-wdc#229]
Used version 3.3.x succesfully. 
Just updated to version 3.4.0. Removed old version and deleted all the www-files.
Now I'm getting lots of errors.
Here is pastebin link.

https://pastebin.com/s8dBxmEZ

Debian 12.2, weewx 4.10.2, python 3.11.2 all packages all latest and system rebooted.

**Comment by Daveiano** [comment]
I have never seen these error messages before. Do you just start with a new empty database or do you already have some station data?

Did you install the previous v3.3.x also with python 3.11 or with 3.10? I read about some general weewx problems with 3.11, so a downgrade wo python 3.10 could probably solve this for the moment.

**Comment by iiseppi** [comment]
I have station data about 10 years already. 

I installed version 3.3.x to this same machine in summer, python version was same 3.11.2.
I can test with new machine and debian 12 if I get the same error then.

**Comment by Daveiano** [comment]
> I have station data about 10 years already

Ok, so thats not the problem.

> I installed version 3.3.x to this same machine in summer, python version was same 3.11.2.

And 3.3.x was also running with weewx 4.10.2?

Do these errors appear on each report run or only from time to time?

**Comment by iiseppi** [comment]
> > I have station data about 10 years already
> 
> Ok, so thats not the problem.
> 
> > I installed version 3.3.x to this same machine in summer, python version was same 3.11.2.
> 
> And 3.3.x was also running with weewx 4.10.2?
> 
Yes. And template worked fine then.

> Do these errors appear on each report run or only from time to time?

They appear on each report run and also the template is not generating any files now. 
I try to make new install of weewx with simulator mode and try to install only WDC template to see if I get errors still.

**Comment by Daveiano** [comment]
Ok, that's realy strange, I had another look at your log output.

> They appear on each report run and also the template is not generating any files now.

So I assume you posted not all errors? The errors you provided only affect the daily archive pages, there are more errors? 

> I try to make new install of weewx with simulator mode and try to install only WDC template to see if I get errors still.

Ok, great. Please let me know what happened. I can provide you an updated template within this week, which should solve the problem - but it would be good to know why this is happening ;)

**Comment by iiseppi** [comment]
Ok. Plain install debian 11.8, python 3.9.2 and no problems with WDC. And also did plain install with Debian 12.2, python 3.11.2 and also no problems. These where using weewx in simulator mode.
I think that I must do clean install with my real data and check if the original problem still occur.

**Comment by Daveiano** [comment]
Ok, strange (but good). 

Yes, would be interesting what happens if you use your real database.

**Comment by Daveiano** [comment]
@iiseppi I guess this issue can be closed?

**Comment by iiseppi** [comment]
Aa, sorry, I forgot to update, that this can be closed.
