### ISSUE TITLE
Translation Footer Link Fix

### ISSUE THREAD

**Issue by c0by85** [Daveiano/weewx-wdc#238]
Sorry, but I don't know how I could solve this without countless pull requests. But for every translation the HTML link has to be adapted. `Target='_blank'` was forgotten. That's why the translation doesn't work.

This must also be changed in the translated text.

Wrong:

`"This station is controlled by <a href='https://weewx.com'>WeeWX</a>, an experimental weather software system written in Python."`

Correct: 

`"This station is controlled by <a target='_blank' href='https://weewx.com'>WeeWX</a>, an experimental weather software system written in Python."`

![image](https://github.com/Daveiano/weewx-wdc/assets/25707747/fe4da790-dd80-4a17-ac05-210cdc3e6169)

**Comment by Daveiano** [comment]
Hello there, thanks for reaching out and: no need for apologies! What was wrong with PR #237? Looks good to me.

However, you are right, the `target="_blank"` is missing in the translation files. I fixed this in [cb9df0b](https://github.com/Daveiano/weewx-wdc/commit/cb9df0b53bace5e3aa53240b1967814beb3bb5ee), the change will be included in the next release.

**Comment by c0by85** [comment]
fixed with https://github.com/Daveiano/weewx-wdc/commit/cb9df0b53bace5e3aa53240b1967814beb3bb5ee
