### ISSUE TITLE
Default dark mode

### ISSUE THREAD

**Issue by dystechnic** [Daveiano/weewx-wdc#241]
**Is your feature request related to a problem? Please describe.**
Whenever the browser is reloaded (closed and opened again) the skin defaults back to light mode. Probably because cookies are removed?

**Describe the solution you'd like**
Is it possible to make dark-mode the default so whenever someone opens the site it will be dark until they select light on purpose?  

**Describe alternatives you've considered**
None

**Comment by Daveiano** [comment]
It shouldn't be like that!

The skin should "remember" the current theme (light/dark) even if you close the browser and re-open it. The setting gets saved via `localStorage` (see https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) in the browser.

Could you please test this with my private page?

Go to https://www.weewx-hbt.de/, and activate dark mode. Then close the tab or the whole browser and visit the page again, it should still be in dark mode.

If it shows up in light theme, something with you browser seems to be fishy, perhaps only private browsing allowed?

**Comment by dystechnic** [comment]
I tried it with https://www.weewx-hbt.de/ and the result is the same.
Darkmode settings seem to be stored locally. Because we are using the system in a semi-public area we remove all history, cookies, etc every time the browser closes. And it seems that with that the darkmode prefference is deleted also.

**Comment by Daveiano** [comment]
@dystechnic I added a new configuration, from the (not yet published) wiki:

> `default_theme` One of 'light', 'dark' or 'auto'. If set to 'auto', the skin will use the OS/browser's setting. If the browser is set to dark mode, the skin will use the dark theme, otherwise the light theme. If you want to force the dark mode, set `default_theme` to 'dark'.

I released a pre-release to test this out: https://github.com/Daveiano/weewx-wdc/releases/tag/v3.5.0-alpha2

**Comment by dystechnic** [comment]
I tried it and it works as expected.
Great job! Thank you. I'll wait for the official release.
