### ISSUE TITLE
Colored Temperature

### ISSUE THREAD

**Issue by c0by85** [Daveiano/weewx-wdc#243]
Could please add colored Temperature? Like in the Belchertown Skin?

![image](https://github.com/Daveiano/weewx-wdc/assets/25707747/b8b589e4-318c-4bea-97c5-ed3c7dce90bc)

**Comment by Daveiano** [comment]
You are thinking about the temperature in the stat tile on the top, right?

![243](https://github.com/Daveiano/weewx-wdc/assets/3184897/a2786dad-2d40-4100-af61-43e029e5082a)

**Comment by c0by85** [comment]
Sorry forgot to include. Yes, right there.

**Comment by Daveiano** [comment]
Will be included in the next release! Here are some preview screenshots:

![wdc-243-3](https://github.com/Daveiano/weewx-wdc/assets/3184897/5b4d6e8a-7151-437f-9001-38d52c7efdd9)
![wdc-243-2](https://github.com/Daveiano/weewx-wdc/assets/3184897/86f34ae4-db03-444f-80cd-d8fe9049c213)
![wdc-243-1](https://github.com/Daveiano/weewx-wdc/assets/3184897/0f31dc71-a6d3-4e8d-a2ad-5fe40cb9bdd0)

**Comment by gary-hammer** [comment]
While I like the idea of different colors for the temp, I'm not a fan of having my monochrome display have a block of changing color.

Is there a way to simply color the data, numeric temperature itself, and leave the rest of the block alone?

**Comment by Daveiano** [comment]
Understandable. I will have a talk about this with my design-colleagues ;)

Issue is reopened and re-planned for the next release.

**Comment by gary-hammer** [comment]
Thank you

**Comment by Daveiano** [comment]
@gary-hammer 

> my monochrome display

Wouldn't it be best to completely disable the coloured temperature if using a monochrome display? I guess if only the number is coloured, it does not add any value to the display either!?

**Comment by gary-hammer** [comment]
When I said monochrome, I mean the current look of the display. 
I run on an Android tablet, it has color if course. 

Perhaps just change the color of the numbers and leave the rest of the card alone

**Comment by Daveiano** [comment]
@gary-hammer 

Here is an updated colored-temperatur.js file: [colored-temperature.js.zip](https://github.com/user-attachments/files/17879442/colored-temperature.js.zip). Please feel free to copy that to your `skins/weewx-wdc/dist` directory.

You will also need to set this in your skin.conf:

```
[DisplayOptions]
    ...
    outTemp_stat_tile_color_text_only = True
```

And this change to `skins/weewx-wdc/includes/html-head.inc` https://github.com/Daveiano/weewx-wdc/commit/7f0b4ae73a91b7205e2ad92246a772735a14faa6#diff-dcc676d8bd36207fe0688d62d18851f93f457c5bb6530e35209128df1d8d2de1

**Note:** Its best to also set `outTemp_stat_tile_color_transparency = 1`

Please let me know if that works and looks good to you!

**Comment by gary-hammer** [comment]
I have installed the new file and made the changes indicated. Erased the output directory. Waited for a report cycle, then weectl report run to make sure all files were there and current.

So, how to get colors? My display looks the same, kinda gray. numbers.

Attaching the changes made.
[wdc-color.txt](https://github.com/user-attachments/files/17882030/wdc-color.txt)

**Comment by Daveiano** [comment]
Do you have `outTemp_stat_tile_color = True` set in your skin.conf?

You do not need to add this at the top of the file, it should already be present in the skin.conf: https://github.com/Daveiano/weewx-wdc/blob/v3.5.1/skins/weewx-wdc/skin.conf#L152-L156

**Comment by gary-hammer** [comment]
Of course not <g>.
It is default, False.
Made the change, ran the report, presto!
So, is the color temperature sensitive? Meaning blueish when < 32F red > 90F, etc.
I'm going to guess this is the color changing section:
    outTemp_stat_tile_color_min = -20
    outTemp_stat_tile_color_max = 40


Attached is what it looks like with the changes I've made.

Thanks!
![color](https://github.com/user-attachments/assets/81e98424-cd83-4e6d-9b83-32f93196680c)

**Comment by Daveiano** [comment]
> Meaning blueish when < 32F red > 90F, etc. I'm going to guess this is the color changing section: outTemp_stat_tile_color_min = -20 outTemp_stat_tile_color_max = 40

Yes, exactly. You can read more about it here: https://github.com/Daveiano/weewx-wdc/wiki/Configuration

I guess the issue can be closed now?

**Comment by gary-hammer** [comment]
Yes sir, though I'm not the OP, for me it can be closed.
Thank you for the change.
I'm glad your design department agreed!

**Comment by Daveiano** [comment]
> I'm glad your design department agreed!

Not completely, but sometimes a happy user is more desirable ;)
