### ISSUE TITLE
Windrose legend overlaps under mobile when using knots [BUG]

### ISSUE THREAD

**Issue by nicholaswaton** [Daveiano/weewx-wdc#249]
Hello

I noticed that because we are using knots, the legend for the windRose overlaps a lot on mobile. Also, seeing "knots" so many times seems redundant.
I was wondering if it would be possible to remove the unit (leaving just the range in numbers)?

This is what I see on mobile:
![IMG_3177](https://github.com/Daveiano/weewx-wdc/assets/125936903/9d3c6db8-3432-42e4-a7c6-1e69b11ce2c0)

I also removed the units from the ticks on Gauges, for a cleaner look but I couldn't figure how to do it on the windRose.
<img width="285" alt="Screenshot 2024-02-03 at 12 48 32" src="https://github.com/Daveiano/weewx-wdc/assets/125936903/c3ca3d4e-8a45-4d6c-a8ab-0064f650780f">

thank you!

**Comment by Daveiano** [comment]
Hello!

> I noticed that because we are using knots, the legend for the windRose overlaps a lot on mobile. Also, seeing "knots" so many times seems redundant.
I was wondering if it would be possible to remove the unit (leaving just the range in numbers)?

I added a new configuration, `windRose_legend_show_units`. When set to True, the unit labels are not shown in the legend. Instead, the unit is shown once above the legend:

![Screenshot](https://raw.githubusercontent.com/Daveiano/weewx-wdc/3.x/test/e2e-tests/diagrams/diagrams.test.ts-snapshots/Diagrams-Windrose-with-non-beaufort-untis-and-without-unit-labels-2-chromium-linux.png)

This should hopefully fix the overlapping text. The new configuration will be included in the next upcoming release!

> I also removed the units from the ticks on Gauges, for a cleaner look but I couldn't figure how to do it on the windRose.

May I ask, how you did this? Probably this should be also configurable?

**Comment by nicholaswaton** [comment]
That looks great!

For the Gauge, I went in the javascript code in main.js and removed the part where it adds the unit to each tick. It was challenging to find as it was minified, but I figured it out. It would definitely be great if it could be configured.

I love also the new option for the legend position. It was also bothering me as it was often too close to the graphs.

**Comment by Daveiano** [comment]
> For the Gauge, I went in the javascript code in main.js and removed the part where it adds the unit to each tick. It was challenging to find as it was minified, but I figured it out. It would definitely be great if it could be configured.

Sounds like a bit pain in the... I added `hide_tick_unit` for configuring this, will be included in 3.5.0, too.

> I love also the new option for the legend position. It was also bothering me as it was often too close to the graphs.

Great, happy to hear that!
