### ISSUE TITLE
[BUG] Stat tile on page Today using custom data binding does not appear if the same observation does not exist in main data binding

### ISSUE THREAD

**Issue by bidord** [Daveiano/weewx-wdc#258]
**Describe the bug**

A stat tile on page Today targetting an observation for a custom data binding does not appear if there is no data for the same observation on the main data binding.

**To Reproduce**

`weewx.conf`:

```ini
[StdArchive]
  data_binding = wx_binding
  # ...

[DataBindings]
  [[wx_binding]]
    # ...
  [[wx2_binding]]
    # ...
```

- `wx_binding` has data for `inTemp` but no data for `extraTemp1`
- `wx2_binding` has data for both `inTemp` and `extraTemp1`

`skin.conf`:

```ini
[ObservationBindings]
  [[wx2_inTemp]]
    data_binding = wx2_binding
    observation = inTemp
  [[wx2_extraTemp1]]
    data_binding = wx2_binding
    observation = extraTemp1

[DisplayOptions]
  stat_tile_observations = inTemp, wx2_inTemp, wx2_extraTemp1
```

Page "Today" has a stat tile for `inTemp` and `wx2_inTemp`, but the stat tile for `wx2_extraTemp1` does not appear.

On other pages the three stat tiles appear as expected.

**Expected behavior**

The stat tile for `wx2_extraTemp1` should appear on page "Today".

**Comment by Daveiano** [comment]
Thank you for the detailed report and the PR, it is very appreciated!

The change looks reasonable to me, did you test this by yourself? Do all observations show up as expected with the fix?

**Comment by bidord** [comment]
You are welcome. I'm glad I can make a contribution to this amazing project!

Yes, I've been testing this on my "production" weewx instance for the last 2 days.

I have a Vantage Pro 2 station. I recently bought an Ecowitt GW2000 to be used as a secondary station in order to add a bunch of extra temperature/humidity sensors. That's how I noticed this bug on the "Today" page.

I can confirm that with this patch:
- The original bug does not occur anymore ( the `extraTempX` and `extraHumidX` of my secondary station do show up on every page where they should).
- So far, everything else seems to keep working as expected.

**Comment by Daveiano** [comment]
Merged.

Thanks again for the detailed report and the PR!
