### ISSUE TITLE
Add Moon phases translations

### ISSUE THREAD

**Issue by aryiu** [Daveiano/weewx-wdc#264]
**Is your feature request related to a problem? Please describe.**
No possibility of translating Moon phases in _Celestial_ page.
<img width="300" alt="moon-phases" src="https://github.com/Daveiano/weewx-wdc/assets/130826840/0cb4bb3b-775c-4b9c-a78c-b98a100258c0">

**Describe the solution you'd like**
- Add a way for getting these words translated in your translation file (i.e. `it.conf`) 
- Also, maybe it would be great to add by default the planet name strings, although **these translations work right now** if you add the strings manually. For example: `"Mars" = "Marte"` (and it's shown correctly)

**Comment by Daveiano** [comment]
Added in [8006446](https://github.com/Daveiano/weewx-wdc/commit/8006446396fa5c2f0eaf69608d35bb9f991451f1) and will be included in the next release.

You can translate the moon phases by adding something like this to `it.conf`:

```
[Almanac]
    # The labels to be used for the phases of the moon:
    moon_phases = Nuova, Crescente, Primo quarto, Gibbosa crescente, Piena, Gibbosa calante, Ultimo quarto, Calante
```

I also added defaults for the planet names in `it.conf`:

```
    "Mars" = "Marte"
    "Jupiter" = "Giove"
    "Saturn" = "Saturno"
    "Venus" = "Venere"
```

**Comment by aryiu** [comment]
Thank you! You can also add this in the `[Texts]` section of `it.conf` for translating the card tags:

```
 "Phase" = "X"
 "New moon" = "X"
 "Full moon" = "X"
```

**Comment by Daveiano** [comment]
@aryiu You are right, some translations were missing. I added everything I found untranslated, and it looks good to me:

![GH-264](https://github.com/user-attachments/assets/27993602-e3d1-47b3-83f6-a8d20f196ee5)

You can test it by copying the updated translations files into your skin dir locally from https://github.com/Daveiano/weewx-wdc/tree/3.x/skins/weewx-wdc/lang

Please let me know if you find something left untranslated!
