### ISSUE TITLE
[BUG] statistics.html problem

### ISSUE THREAD

**Issue by barci335** [Daveiano/weewx-wdc#277]
**Describe the bug**
Rain days not showing up on the statistics.html page. (works on year-20xx.html page)
Also no diagram on Rain Tab. (works on year-20xx.html page)

**To Reproduce**
1. Clean, fresh installation of weewx 5.1.0 with wdc 3.5.1
2. Click on Statistics Page
3. See error

**Expected behavior**
Statistics Page should show rain days and rain diagram. 

**Screenshots**
Statistics Page: Total rain days show 0
![image](https://github.com/Daveiano/weewx-wdc/assets/32842368/b1ed7201-d650-43ff-828f-99f040043f24)
![image](https://github.com/Daveiano/weewx-wdc/assets/32842368/74cc8fd2-fe3b-4c4f-bfec-143327e4c93d)

Yearly Page:
![image](https://github.com/Daveiano/weewx-wdc/assets/32842368/420a313c-8004-4744-81e0-68fdb5b35dbb)
![image](https://github.com/Daveiano/weewx-wdc/assets/32842368/de699bc7-9d77-4511-98a5-e17197317711)

**Additional context**
No warning/error in syslog found.

Thanks in advance

**Comment by Daveiano** [comment]
How many years of data do you have? The stats page shows that there is only data for 07/07/24 to 08/07/24?

**Comment by barci335** [comment]
As i said in my first post, fresh installation + new database. Only the first day is not counting for some reason. I can live with that.
![image](https://github.com/user-attachments/assets/a63ba38d-8994-461d-8d99-96eaf428f1e4)

**Comment by Daveiano** [comment]
Oh ok I got you. Had a quick look over the relevant code but did not spot anything obvious. 

Could you share your weewx db with me? This would be extremely helpful for debugging.

**Comment by Daveiano** [comment]
Closed issue due to inactivity. Please leave a comment if you feel this should be addressed.
