### ISSUE TITLE
Add time to temp cards.

### ISSUE THREAD

**Issue by iiseppi** [Daveiano/weewx-wdc#284]
Hi,

Is it possible to add time for each "card" in front page when was eg. minimum/maximum  temperature after the readings? 
There should be space enough?
![add_time](https://github.com/user-attachments/assets/a679d312-aa9b-4475-92ad-f9e665200004)
Thank you!

**Comment by Daveiano** [comment]
Hi @iiseppi 

that should be already possible via skin.conf: https://github.com/Daveiano/weewx-wdc/blob/3.x/skins/weewx-wdc/skin.conf#L147

Its also described here: https://github.com/Daveiano/weewx-wdc/wiki/Configuration#displayoptions (search for `show_min_max_time_day`)

**Comment by iiseppi** [comment]
Ah, I see. Thank you!
I somehow missed that! 
Any news about next version of skin? :)

**Comment by Daveiano** [comment]
> Any news about next version of skin? :)

I will try to release 2 feature releases for the skin per year, so there will be a new release within this year (I hope so - its a lot of workload).
