### ISSUE TITLE
Time is Not Correct In All Data

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#40]
I notice the time displayed for All Data is off by 2 hours.
It is correct elsewhere (under current weather conditions, forecasts, etc)

No idea why it is 2 hours off (early, 9:40 AM is listed as 7:40 AM) it would be a DST thing with a 2 hour difference.

**Comment by Daveiano** [comment]
@gary-hammer Did you notice this on the index page? If so, the values in the "All data" table are not really all data. They are aggregated. In the case of the index page, the aggregation interval is set to 2h. The time shown in the table is the start time of this record. 

That way it's always 2h off the current time.

I guess on the week page the time is off by 6h? since this is the aggregation period for the week pages table data.

Would it make more sense to show the end time of the record? That way it would be the current time.

**Comment by gary-hammer** [comment]
Yes, both are the way it is here. And confusing (to me) even after knowing why.
For me, Id rather have the time of the latest record. As is, it isn't the past 24 hours of data but rather a snapshot that was last taken 2 hours before.

BTW- Why the 2hr aggregation interval on the Day page instead of hourly? The skin doesn't seem to take long to generate.

Aug 02 05:55:18 lts weewxd[17545]: weewx[17545] INFO weewx.cheetahgenerator: Generated 9 files for report WdcReport in 0.81 seconds
Aug 02 05:55:18 lts weewxd[17545]: weewx[17545] INFO weewx.reportengine: Copied 10 files to /home/web
Aug 02 05:55:18 lts weewxd[17545]: weewx[17545] INFO weewx.cheetahgenerator: Generated 12 files for report forecast in 0.35 seconds
Aug 02 05:55:18 lts weewxd[17545]: weewx[17545] INFO weewx.reportengine: Copied 89 files to /home/web/forecast

**Comment by Daveiano** [comment]
Just for clarification: I get the following data from weewx, current time for this example is 20:00 (example just includes the outTemp):

|start | end | outTemp|
|------|-------|------------|
|12:00:00 | 14:00:00  | 43.8°F|
|14:00:00  | 16:00:00  | 43.2°F|
|16:00:00  | 18:00:00  | 42.7°F|
|18:00:00  | 20:00:00  | 41.3°F|

So the average outTemp was 43.8°F for the time from 12:00 to 14:00. 43.2°F from 14:00 to 16:00 and so on...

The date column in the table currently shows the `start` time, but it should show the `current` time. Does this make sense to you?

> BTW- Why the 2hr aggregation interval on the Day page instead of hourly? The skin doesn't seem to take long to generate.

On larger datasets and small machines, it takes some time, see #14. But you are right, 1h would be appropriate for the daily table, I will add this.

**Comment by gary-hammer** [comment]
I think the current or when generated time makes sense.

Thanks for the hourly interval.

**Comment by Daveiano** [comment]
I added the hourly interval and also the change described in https://github.com/Daveiano/weewx-wdc/issues/40#issuecomment-1202784287 (show the stop instead of the start date - which is basically the current time).

This will be available in the upcoming 2.0.1 release.

Thank you for your feedback!

**Comment by gary-hammer** [comment]
Thank you.
