### ISSUE TITLE
NWS Forecast?

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#42]
I see the WU forecast is predefined, how can I change to the NWS forecast?

**Comment by Daveiano** [comment]
@gary-hammer Please have a look at the readme: https://github.com/Daveiano/weewx-wdc#support-for-weewx-forecast:

> ...
> Please set `source` to your used forecast source. 
> ...

So, for NWS it would be:

```
[[forecast_table_settings]]
        source = NWS
        num_periods = 72
        num_days = 5
        show_legend = 1
        show_hourly = 0
        show_day = 1
        show_date = 1
        show_outlook = 1
        show_temp = 1
        show_dewpoint = 0
        show_humidity = 0
        show_wind = 1
        show_tides = 0
        show_sun = 1
        show_moon = 1
        show_pop = 1
        show_precip = 1
        show_obvis = 0
```

The config is the same for all forecast providers. It's just the source that changes.

Does this solve your problem? Wondering if the readme needs to be clearer on that?

**Comment by gary-hammer** [comment]
I came to that realization by looking at the skin.conf included with the forecast where I found the providers.
I also looked at the forecast.py file and found that you need only the forecast services you use in weewx.conf
I had errors at every startup for the forecasts I had not configured/used.

archive_services = weewx.engine.StdArchive, user.forecast.ZambrettiForecast, user.forecast.NWSForecast, user.forecast.WUForecast

Yes, I think that part of the readme could be made more complete/clear.

**Comment by Daveiano** [comment]
Yes, the first part is to configure weewx-forecast and the second part is to update the skin.conf (adding the SLE's and updating the forecast_table_settings).

Ok, I will update the readme on that and close the issue when done.

**Comment by Daveiano** [comment]
I updated the readme, see https://github.com/Daveiano/weewx-wdc#support-for-weewx-forecast.

I hope this helps for future installations, if something is missing, please let me know!

**Comment by gary-hammer** [comment]
Looks clearer to me.
Thanks

**Comment by gary-hammer** [comment]
Yes, once I got it, simple.
It was the multiple sources to get the info that took time.
