### ISSUE TITLE
Forecast Min/Max

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#43]
The min max for temp on the WU forecast looks odd and is not needed as the larger and smaller different color numbers in the forecast should be self explanatory.

![example-3](https://user-images.githubusercontent.com/12861605/182170215-ae062a8b-499b-46c7-8633-fa50860cae01.png)

**Comment by Daveiano** [comment]
Yeah, it should be pretty clear what these values mean. Even if you consider that some people have problems with colours, this should be clear.

**Comment by gary-hammer** [comment]
Thank you.
