### ISSUE TITLE
Windchill is not translated to Windkühle in German

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#50]
![grafik](https://user-images.githubusercontent.com/61492037/183492177-948f2c38-8262-48a9-a219-60ebdfe39587.png)

**Comment by Supergamerx3000** [comment]
![grafik](https://user-images.githubusercontent.com/61492037/183492489-71e5b4b2-35a8-401e-8abe-203c97312b29.png)

meters is also in english

**Comment by Daveiano** [comment]
Will be included in an upcoming release, thank you!
