### ISSUE TITLE
change wind unit from beaufort to km/h (opt-in)

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#51]
the beaufort scale is more for seafarers. I would like to see the graph with km/h like the values are shown above

![grafik](https://user-images.githubusercontent.com/61492037/183495003-b57dba3d-c67a-46ae-bc16-76249e9b70d6.png)

**Comment by Daveiano** [comment]
@Supergamerx3000 Please have a look at the screenshot:

![weewx-wdc-gh-51](https://user-images.githubusercontent.com/3184897/187485890-b59a3d13-faee-43c1-bf26-8d94044291c7.png)

The scales (7km/h - 11km/h or 31km/h - 39km/h) are still the Beaufort scale, but the values are shown as km/h (or m/s if using this unit). 

Is this what you intended?

**Comment by Supergamerx3000** [comment]
@Daveiano is there a different scale for km/h?  You probably mean the different wind speeds that are reached from a certain number of km/h?  do you get them displayed on the left?

**Comment by Daveiano** [comment]
It's just the labels that changed. For example, if using km/h (metric) units:

Instead of **Beaufort 2**, **6–11 km/h** will be shown.

Will be included in 2.3.0
