### ISSUE TITLE
Show Yesterday in the top bar

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#52]
It would be very nice if I could go back one day and look at yesterday's values.

Or is this already possible? But i don't see the Button?

**Comment by Daveiano** [comment]
Currently, there is no "Yesterday-page" implemented. But this would not be too difficult to implement, I will put this on the agenda for future releases.

**Comment by Daveiano** [comment]
Will be included in 2.3.0.
