### ISSUE TITLE
Grafik Bodenfeuchte

### ISSUE THREAD

**Issue by jernst01** [Daveiano/weewx-wdc#60]
Es sind bei mir die Sensoren soilMoist1 und soilMoist2 belegt. Beide liefern Werte aus, die auch nummerisch in der linken Spalte dargestellt werden. Nun möchte ich dies auch grafisch darstellen.
Hierzu habe ich die skin.conf wie folgt erweitert:
 [[[[soilMoist]]]]
                label = 'Bodenfeuchte'
                pointSize = 3                     
                    [[[[[obs]]]]]
                    [[[[[[soilMoist1]]]]]]
                        observation = "soilMoist1"
                        aggregate_type = "max"
                        color = '#610000' 
                    [[[[[[soilMoist2]]]]]]
                        observation = "soilMoist2"
                        aggregate_type = "max"  
                        color = '#410000' 
Leider wird nichts angezeigt.
Wo liegt mein Denkfehler / was habe ich falsch gemacht?
Danke

**Comment by Daveiano** [comment]
Haben sie `soilMoist1` und `soilMoist2` auch unter `diagram_tile_observations` hinzugefügt?

Falls ja und es funktioniert nicht, ist es ein Fehler im Skin. Leider kann ich das ganze nicht testen weil ich keine Sensoren für die Bodenfeuchte besitze. Wäre es möglich, mir die weewx.sdb (weewx datenbank) zum Testen zur Verfügung zu stellen (siehe https://weewx.com/docs/usersguide.htm#Where_to_find_things, "SQLite databases")?

**Comment by jernst01** [comment]
Nein das hatte ich nicht. Habe es nachgeholt und nun geht es wunderbar.
Vielen Dank und weiterhin viel Erfolg mit dem wirklich gelungenen Skin
