### ISSUE TITLE
Show weather data for a specific day

### ISSUE THREAD

**Issue by Supergamerx3000** [Daveiano/weewx-wdc#67]
**Is your feature request related to a problem? Please describe.**
No only a Feature Request

**Describe the solution you'd like**
If I go to statistics, the entire data period is currently displayed.

I would like to change the dates above to see a specific day. So I can also see the high/low temp, wind data, rain etc... from that specific day that I have selected.

![grafik](https://user-images.githubusercontent.com/61492037/188238035-b7e1db1b-a8f8-492d-8d1d-42229c5622e6.png)

**Comment by Daveiano** [comment]
This sounds like a big thing to me, I don't know of any weewx skin with this ability!?

I am also very interested in this feature so I will have a look! Will come back to the issue when I got time to think/test an implementation.

_Just some technical thoughts:_
I could imagine this could be implemented via MQTT, but I am not an expert on that but I will have a look at this. Another option would be to generate a big JSON file which contains all values from the database, so the skin could dynamically get/calculate the values needed for the chosen day or day range.

**Comment by Jterrettaz** [comment]
I am afraid that a big JSON containing all the values of the database would take more and more time being generated, given the fact that the database will grow with time. Having 17 years of data in my database, it would take  a very long time to generate and to be transferred by FTP.
On my side, I have modified your skin so that, additionally to historical month and years,  it generate historical daily pages  using a `day-%Y-%m-%d.html.tmpl ` template file.  This template file is almost the same as your  index.html.tmpl  file.
It take some time during the first run to generate all the daily files, but then only the file of the current day is updated and transferred by FTP.
Here is my "Archive" page - http://meteo-sciez.fr/site/archives.php - where one can select a day and see either the data of this day, of the month, or of the year.

**Comment by Supergamerx3000** [comment]
wow your weather page is very cool.

Did you design it entirely yourself?

**Comment by Jterrettaz** [comment]
yes, I designed most of the page of my site by myself

**Comment by Daveiano** [comment]
@Jterrettaz & @Supergamerx3000 Thanks for the input!

> I am afraid that a big JSON containing all the values of the database would take more and more time being generated, given the fact that the database will grow with time. Having 17 years of data in my database, it would take a very long time to generate and to be transferred by FTP. 

My idea was not to rewrite the file every time. I was thinking more about appending the new data, let's say, twice a day. I have no idea yet how to implement that but I guess this could work (some kind of custom weewx service?).

With this implementation, it would also be possible to query a custom day-range. For example, the last two weeks of august last year or whatever you can imagine.

> On my side, I have modified your skin so that, additionally to historical month and years, it generate historical daily pages using a `day-%Y-%m-%d.html.tmpl ` template file. This template file is almost the same as your index.html.tmpl file. It take some time during the first run to generate all the daily files, but then only the file of the current day is updated and transferred by FTP. 

This sounds like a quick way to achieve this for every day, I think this could be added into the skin pretty easily. Thanks for this reminder! I will rethink about this a bit, but I think to could be added as an opt-in feature to the skin.

**Comment by Daveiano** [comment]
So I tested around with MQTT, but this is not an option for historical data (had never worked with it before, but it's the way for implementing live data updates for the skin, but that's another issue ;)). 

@Jterrettaz I think I will include your solution to the skin, thank you again for this idea!

Maybe in the future, the skin will include a feature to select not only a specific day but a user-defined date range of days, months or whatever.

**Comment by Supergamerx3000** [comment]
@Daveiano i have updated my weewx an weewx wdc also reanabled the archive https://github.com/Daveiano/weewx-wdc/wiki/Daily-archive the daily archive files are accessible over https://wetter-reichelsheim.de/day-archive/day-2022-08-07.html

but in the statistics page the dropdown menü is not shown
