### ISSUE TITLE
Threshold for rain to define Rain days

### ISSUE THREAD

**Issue by hoetzgit** [Daveiano/weewx-wdc#80]
I would like to have the ability to set the threshold for rain to define rain days. The DWD defines e.g. a rain day from an amount >= 0.1mm. [DWD](https://www.dwd.de/DE/service/lexikon/Functions/glossar.html?lv3=102196&lv2=102134)
(if this does not already exist and I have overlooked it).

**Comment by hoetzgit** [comment]
Is done, have now read correctly and seen that rain > 0.0 mm is evaluated.

**Comment by Daveiano** [comment]
Yes this defined here: https://github.com/Daveiano/weewx-wdc/blob/2.x/bin/user/weewx_wdc.py#L1064
