### ISSUE TITLE
Bugfixes weewx-wdc Version 2.3.0

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#81]
### Discussed in https://github.com/Daveiano/weewx-wdc/discussions/79

<div type='discussions-op-text'>

<sup>Originally posted by **hoetzgit** October 17, 2022</sup>
@Daveiano

Hallo David,

ich bin etwas vorsichtig Issues zu generieren, weil ich eigene Fehler in meiner Konfiguration nicht ausschließen kann. daher diese Vorphase:

weewx-DWD Einbindung:

- Bei der Vorhersagetabelle habe ich offensichtlich bei lang=de ein Umlautproblem. Habe versucht, bspw. "ö" durch `&ouml;` zu ersetzen, ohne Erfolg. Auch scheinen in die `de.conf` z.B. Zeile `216` noch ein paar Zeichen zusätzlich mit reingerutscht zu sein.
- Leider sind deutsche Bezeichnungen oft sehr lang. So reicht z.B. "Niederschlagswahrscheinlichkeit" bis in den Wertebereich hinein und überschreibt diesen. Gibt es eine Möglichkeit, eine Worttrennung zu erreichen?
- Die Warnkarte "SchilderXX.jpg" ist evtl. statisch programmiert?

Benötigst Du weitere Infos, melde Dich gerne.
Siehe auch [Webseite](https://wdc.weiherhammer-wetter.de)

Grüße
Henry</div>

**Comment by Daveiano** [comment]
Das sind definitiv 3 Bugs die unter der deutschen Sprache auftreten, kann ich mit meiner lokalen Installation nachvollziehen.

Das mit der Warnkarte "SchilderXX.jpg" ist mir gar nicht aufgefallen weil der Standardwert Sachsen ist, was für mich auch zutrifft. Musste ich also nie ändern, deswegen habe ich das übersehen. 

Da man das händig in [`wget-dwd`](https://github.com/roe-dl/weewx-DWD/blob/master/usr/local/bin/wget-dwd#L14) angeben muss, wird man das dann noch ein zweites mal in der skin.conf setzen müssen.

Zur Erklärung: Die Zeichen in der `de.conf` sind beabsichtigt. `&shy;` ist ein Bedingter Trennstrich. Das heißt da wird nur eine Trennung vorgenommen wenn es aus Platzgründen auch nötig ist. Mehr dazu hier: https://de.wikipedia.org/wiki/Bedingter_Trennstrich. Nur sollte der Skin das auch rendern und nicht als Text darstellen, das ist der Fehler.

**Comment by hoetzgit** [comment]
@Daveiano 
Vielen Dank für die Optimierungen und auch für die Erklärung zu `&shy;` - wieder etwas gelernt.

**Comment by Daveiano** [comment]
@hoetzgit Gerne. Ich werde noch bis etwa Ende der Woche warten ob noch mehr Feedback zur 2.3.0 kommt und ansonsten ein Bugfix-Release veröffentlichen, da werden die Fixes von dem Issue hier und #83 enthalten sein.
