### ISSUE TITLE
Ansicht "Vorhersage vom DWD"

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#86]
### Discussed in https://github.com/Daveiano/weewx-wdc/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **hoetzgit** October 20, 2022</sup>
Hallo David,

ich möchte Dich nicht überstrapazieren, aber was hältst Du davon, die Vorhersage etwas zu strukturieren? (Muster: DWD Seite)

Beispiel:

![image](https://user-images.githubusercontent.com/41108116/196924742-e3f9f157-58ac-442f-93e7-e49613076cf8.png)
</div>

**Comment by hoetzgit** [comment]
@Daveiano 

Der DWD hat ja in seinen Vorhersagetexten nochmals gewisse Merkmale (GEWITTER:/NEBEL:/WIND/STURM: ...) unterteilt. In Sachsen aktuell "WIND:") Ich habe jetzt mal nach dem `wget` der Texte auf die Schnelle ein `sed` gemacht und diese Merkmale mit `<b>` und `<br>` versehen. Evtl. könntest Du dies aber auch in Deiner Skin schöner und mit den entsprechenden Klassen formatieren. Das sieht dann bspw. so aus:

![image](https://user-images.githubusercontent.com/41108116/196942919-7e14a39d-7ba2-4f52-9821-459941356dcb.png)

**Comment by Daveiano** [comment]
So etwas (Manipulation der Daten vom DWD) würde ich eher bei [weewx-DWD](https://github.com/roe-dl/weewx-DWD) direkt in `wget-dwd` sehen als im Skin. Der Skin zeigt nur an was er bekommt. Denke das sollte man dort anbringen und vielleicht als optional implementieren.

**Comment by Daveiano** [comment]
![Screenshot from 2022-10-21 02-01-27](https://user-images.githubusercontent.com/3184897/197081390-bee5ef78-8395-4b17-a5ec-900f21a42717.png)

Ich hätte es jetzt so eingebaut, was hälst du davon?

**Comment by hoetzgit** [comment]
Sehr gut! Viel besser lesbar finde ich.

**Comment by hoetzgit** [comment]
Ich habe Deine Änderungen für die DWD Seite eingebaut, dabei ist mir was komisches aufgefallen: Die Schriften sind irgendwie so "verkrummelt", egal welchen Browser ich benutze. Habe auch mal auf Deine Seite geschaut, da ist es genauso.

![image](https://user-images.githubusercontent.com/41108116/197215812-65e481d0-15bb-48f2-bb19-b255c5436945.png)

**Comment by Daveiano** [comment]
Du meinst, das das so ein bisschen "ausgefranst" aussieht oder? Sieht bei mir nicht so aus würde ich meinen:

![Screenshot from 2022-10-21 18-10-07](https://user-images.githubusercontent.com/3184897/197241025-a9607078-6f75-4b28-86b4-873dd845fc59.png)

Welche Betriebssytem/Browser Kombination nutzt du? Kannst du das auch bei anderen Texten auf der Seite feststellen?

**Comment by hoetzgit** [comment]
Ja, genau "ausgefranst" ist das bessere Wort. Komisch, auch auf Mobile/Tab ist die Darstellung völlig ok. Der Screenshot ist auf einem Win11 PC entstanden, geprüft mit Firefox und Chrome basierten Browsern (Opera, Chrome, Edge). Ich müsste das mal auf einem Linux System ansehen. Ich kenne mich da nicht aus, aber kann es sein, dass die Schriften irgendwie gerendert werden müssen oder sowas in der Richtung? Aber da das Problem wahrscheinlich irgendwo bei mir liegt kannst Du für Dich einen Haken dran machen.

Viele Grüße und Danke
Henry

**Comment by hoetzgit** [comment]
Da ich Deine Lösung mit Schleife und den Wochentagen sehr schön finde, habe ich das in meiner Anpassung für die Belchertown Skin nachgezogen. Dadurch ist mir noch eine Anpassung bei Dir aufgefallen. Du könntest `gettext` noch in die `$headings` einbauen.

**Comment by Daveiano** [comment]
> Ja, genau "ausgefranst" ist das bessere Wort. Komisch, auch auf Mobile/Tab ist die Darstellung völlig ok. Der Screenshot ist auf einem Win11 PC entstanden, geprüft mit Firefox und Chrome basierten Browsern (Opera, Chrome, Edge). Ich müsste das mal auf einem Linux System ansehen. Ich kenne mich da nicht aus, aber kann es sein, dass die Schriften irgendwie gerendert werden müssen oder sowas in der Richtung? Aber da das Problem wahrscheinlich irgendwo bei mir liegt kannst Du für Dich einen Haken dran machen.
> 
> Viele Grüße und Danke Henry

Mein Screenshot ist von einem Ubuntu, da sieht alles schick aus. Für Windows habe ich das gefunden: https://www.it-zeugs.de/grauslige-unscharfe-schrift-im-browser-chrome.html



> Da ich Deine Lösung mit Schleife und den Wochentagen sehr schön finde, habe ich das in meiner Anpassung für die Belchertown Skin nachgezogen. Dadurch ist mir noch eine Anpassung bei Dir aufgefallen. Du könntest `gettext` noch in die `$headings` einbauen.

Du meinst damit man "Aktuelle Wetterlage", "Heute" und "Morgen" auch ändern kann (Die 2 Wochentagsnamen werden ja generiert)? Ja das macht Sinn!

**Edit**: Eigentlich wäre es auch sinnvoll alle Texte auf der DWD Seite noch in $gettext() zu packen? Ich dachte am Anfang das wäre nicht nötig, da es wohl nur in Deutschland genutzt wird (un eine Übersetzung nicht nötig wäre). Aber es wäre ja auch sinnvoll damit die Texte vom Nutzer einfacher geändert werden können in der de.conf!?

**Comment by hoetzgit** [comment]
> 
> Mein Screenshot ist von einem Ubuntu, da sieht alles schick aus. Für Windows habe ich das gefunden: https://www.it-zeugs.de/grauslige-unscharfe-schrift-im-browser-chrome.html
> 
Das habe ich jetzt überprüft, danke für den Link. War allerdings aktiviert und hat auch keine Verbesserung gebracht. Da das Problem offensichtlich clientabhänging ist, habe ich ja eh keine Chance und ignoriere das jetzt einfach mal.

> 
> Du meinst damit man "Aktuelle Wetterlage", "Heute" und "Morgen" auch ändern kann (Die 2 Wochentagsnamen werden ja generiert)? Ja das macht Sinn!
> 
Ja genau, die drei fest codierten Label.

> **Edit**: Eigentlich wäre es auch sinnvoll alle Texte auf der DWD Seite noch in $gettext() zu packen? Ich dachte am Anfang das wäre nicht nötig, da es wohl nur in Deutschland genutzt wird (un eine Übersetzung nicht nötig wäre). Aber es wäre ja auch sinnvoll damit die Texte vom Nutzer einfacher geändert werden können in der de.conf!?

Diese Überlegungen hatte ich auch, als ich Dir das mit den drei Labels und `gettext` geschrieben habe. Da ich aber gesehen habe wie sorgfältig Du Deinen Code schreibst ist es nur konsequent, wenn Du diese Möglichkeiten nutzt, auch wenn es auf den ersten Blick nicht an jeder Stelle sinnvoll erscheint.

**Comment by Daveiano** [comment]
Ok, habe das bei allen Texten/Überschriften sofern möglich noch hinzugefügt. Wird im nächsten 2.3.1 release drin sein, danke für den Input!
