### ISSUE TITLE
Limit y-axis for wind/gust speed to 0

### ISSUE THREAD

**Issue by Wooza** [Daveiano/weewx-wdc#90]
**Describe the bug**
I'm using version 2.3.0 with the classic layout. I noticed that the graph for wind/gust speed has negative axis values.
While this is just an UX problem, I was wondering if it is possible to limit the y-axis to non-negative values?

**Screenshots**
![image](https://user-images.githubusercontent.com/2823472/198331106-d6115d1e-1f21-4161-b2dc-3fe80eae4ac5.png)

**Comment by Daveiano** [comment]
Yes, you can add `yScaleMin = 0` to the graph config like this (skin.conf, `[DisplayOptions][[diagrams]][[[combined_observations]]]`):

```diff
[[[[wind]]]]
    label = 'Wind speed / Gust speed'
+   yScaleMin = 0
    [[[[[obs]]]]]
        [[[[[[speed]]]]]]
            observation = "windSpeed"
        [[[[[[gust]]]]]]
            observation = "windGust"
```
Looks like a very calm day!

I will include this change in the next release, looks like a good addition as default. Thanks for reporting this!

**Comment by Wooza** [comment]
Thanks for your quick answer. I will change my configuration.
