### ISSUE TITLE
ET Includes Full Last Day Value

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#92]
I'm unsure if this is WeeWX or the skin.
The current day ET is shown and graphed with the previous day's total included in the value.
I'm attaching 2 screenshots which make clear what I am saying.

![ET-1](https://user-images.githubusercontent.com/12861605/199136827-880e843b-5553-42c1-84d7-c772127d2eaa.png)
![ET-2](https://user-images.githubusercontent.com/12861605/199136837-9ab0d865-2410-41c5-8aad-8a7b089b5f66.png)

**Comment by Daveiano** [comment]
Ok looks like a strange bug, I have never seen this before.

A few questions:
- which weewx version are you using, which weewx-wdc version are you using?
- Is this a new issue or did you observe this already earlier?
- Could you please enable the yesterday page and see if the problem is also there?
- Is the rain graph correct or are there also these totals included?

**Comment by gary-hammer** [comment]
WeeWX version: 4.9.1
Skin: Weather Data Center 2.3.1
I have noticed this for a while, but until looking at the graph, was not 100% certain.
How would I enable the yesterday page? The Week page seems to have good data graphed.
Rain is fine, no entry at midnight as ET has.

**Comment by gary-hammer** [comment]
I'm closing this as the skin is not at fault.
The weewx instance this is running on uses MQTT as the data source.
I have a test instance that uses SDR as the data source.
Both are the same Davis unit, just different ways of obtaining the data from it.

The SDR instance does not show the same ET behavior as the MQTT one. As shown by the good and bad snips.

![et-graph-bad](https://user-images.githubusercontent.com/12861605/199501933-f206961e-3e09-4d98-8d4a-ca27422b1989.png)
![et-graph-good](https://user-images.githubusercontent.com/12861605/199501936-6daf6c0d-f27c-4a89-9d50-6dc7fccd2d0e.png)
