### ISSUE TITLE
Since update from 2.20 to 2.3.1 no diagram will be generat [BUG]

### ISSUE THREAD

**Issue by jernst01** [Daveiano/weewx-wdc#97]
Since  my update from 2.2.0 to 2.3.1 no diagram will be generated. I did everything what is to do in your description include 'wee_import'

See here: https://www.juergen-ernst.com/bhw/index.html
 On attache the skin.conf: 

 # configuration file for the weewx-wdc skin
SKIN_NAME = Weather Data Center
SKIN_VERSION = 2.3.1

[Extras]
    # Show a link to the GitHub respository of this skin. Set to False to hide.
    github_link = True

    # The radar image ( or .gif).
    radar_img = https://www.dwd.de/DWD/wetter/radar/radfilm_nib_akt.gif
    # This URL will be used as the image hyperlink:
    radar_url =	https://www.dwd.de/DE/leistungen/radarbild_film/radarbild_film.html
    radar_heading = Recent radar

    [[forecast_zambretti]]
        enable = True

    [[forecast_table_settings]]
        source = WU
        num_periods = 72
        num_days = 5
        # Todo: Does not make sense?
        show_legend = 1
        show_hourly = 0
        show_day = 1
        show_date = 1
        show_outlook = 1
        show_temp = 1
        show_dewpoint = 0
        show_humidity = 0
        show_wind = 1
        show_tides = 0
        show_sun = 1
        show_moon = 1
        show_pop = 1
        show_precip = 1
        show_obvis = 0

    [[weewx-DWD]]
       show_text_forecast = True
       text_forecast_VHDL = DWLG
       dwd_link = https://www.dwd.de/DE/wetter/wetterundklima_vorort/niedersachsen_bremen/nib_node.html
       show_pressure_map = True
       show_warning_map = True
       warning_map_filename = 'SchilderLZ.jpg'
       show_text_warnings = True
       show_warnings_on_front = True
       show_forecast = True
       mosmix_id = 16102
       [[[forecast_table_settings]]]
           show_hourly = 1
           show_date = 1
           show_outlook = 1
           show_temp = 1
           show_dewpoint = 1
           show_pressure = 1
           show_wind= 1
           show_pop = 1
           show_precip = 1
           show_cloud_cover = 1
           show_sun_dur = 1
           carbon_icons = 0

[DisplayOptions]
    layout = 'alternative'
    climatological_days = rainDays, summerDays, hotDays, desertDays, tropicalNights, stormDays, iceDays, frostDays
    table_tile_observations = outTemp, outHumidity, barometer, windSpeed, windGust, windDir, rain, rainRate, snowDepth, dewpoint, windchill, heatindex, UV, ET, radiation, appTemp, cloudbase,soilMoist1, soilMoist2, soilMoist3, soilMoist4, extraTemp1, extraHumid1, extraTemp2, extraHumid2, extraTemp3, extraHumid3, extraTemp4, extraHumid4, extraTemp5, extraHumid5, extraTemp6, extraHumid6, extraTemp7, extraHumid7, extraTemp8, extraHumid8, inTemp
    stat_tile_observations = outTemp, outHumidity, barometer, windSpeed, windDir, windGust, windGustDir, rain, rainRate, snowDepth, dewpoint, windchill, heatindex, UV, ET, radiation, appTemp, cloudbase,soilMoist1, soilMoist2, soilMoist3, soilMoist4, extraTemp1, extraHumid1, extraTemp2, extraHumid2, extraTemp3, extraHumid3, extraTemp4, extraHumid4, extraTemp5, extraHumid5, extraTemp6, extraHumid6, extraTemp7, extraHumid7, extraTemp8, extraHumid8,inTemp
    diagram_tile_observations = temp_min_max_avg, tempdew, outHumidity, barometer, windchill_heatindex, wind, windDir, windRose, rain,soilMoist, rainRate, snowDepth, UV, ET, radiation, cloudbase, appTemp, inTemp
    stat_tile_winddir_ordinal = True
    diagram_tile_winddir_ordinal = True
    show_min_max_time_day = True
    show_min_max_time_yesterday = True
    show_min_max_time_week = True
    show_min_max_time_month = True
    windRose_colors = "#f3cec9", "#e7a4b6", "#cd7eaf", "#a262a9", "#6f4d96", "#3d3b72"
    windRose_show_beaufort = True

    [[tables]]
        [[[day]]]
            aggregate_interval = 3600  # 1 hour
        [[[week]]]
            aggregate_interval = 21600  # 6 hours
        [[[month]]]
            aggregate_interval = 43200  # 12 hours
        [[[year]]]
            aggregate_interval = 86400  # 1 day
        [[[alltime]]]
            aggregate_interval = 86400  # 1 day

    # aggregate_type is only configurable per observatrion (eg. UV or rainRate), not per context (eg. week or month).
    # aggregate_interval is only configurable per context, not per observation in general.
    [[diagrams]]
        [[[combined_observations]]]
            [[[[temp_min_max_avg]]]]
                label = "Temperature Min/Max/Avg"
                pointSize = 3
                yScaleOffset = 0.5
                [[[[[obs]]]]]
                    [[[[[[outTemp_min]]]]]]
                        observation = "outTemp"
                        aggregate_type = "min"
                        color = "#0198E1"
                    [[[[[[outTemp_average]]]]]]
                        observation = "outTemp"
                        aggregate_type = "avg"
                        color = "#666666"
                    [[[[[[outTemp_max]]]]]]
                        observation = "outTemp"
                        aggregate_type = "max"
                        color = "#8B0000"
            [[[[tempdew]]]]
                label = 'Temperature / Dewpoint'
                [[[[[obs]]]]]
                    [[[[[[temp]]]]]]
                        observation = "outTemp"
                    [[[[[[dew]]]]]]
                        observation = "dewpoint"

            [[[[windchill_heatindex]]]]
                label = 'Windchill / Heatindex'
                yScaleOffset = 0.5
                [[[[[obs]]]]]
                    [[[[[[chill]]]]]]
                        observation = "windchill"
                        color = '#0099CC'
                    [[[[[[heat]]]]]]
                        observation = "heatindex"
                        color = '#610000'

            [[[[wind]]]]
                label = 'Wind speed / Gust speed'
                [[[[[obs]]]]]
                    [[[[[[speed]]]]]]
                        observation = "windSpeed"
                    [[[[[[gust]]]]]]
                        observation = "windGust"

            [[[[soilMoist]]]]
                label = 'Bodenfeuchte'       
                    [[[[[obs]]]]]
                    [[[[[[soilMoist1]]]]]]
                        observation = "soilMoist1"
                        color = '#610000'
                    [[[[[[soilMoist2]]]]]]
                          observation = "soilMoist2"
                          color = '#0099CC'

            [[[[extraTemp]]]]
                label = 'Temp: KüKa, Auss, Spibo'       
                    [[[[[obs]]]]]
                    [[[[[[extraTemp1]]]]]]
                        observation = "extraTemp1"
                        color = '#610000'
                    [[[[[[inTemp]]]]]]
                          observation = "inTemp"
                          color = '#0099CC'         
                    [[[[[[outTemp]]]]]]
                          observation = "outTemp"
                          color = '#00FF00'

        # Diagram-type specific settings.
        [[[line]]]
            lineWidth = 2
            pointSize = 5
            isInteractive = True
            enablePoints = True
            enableCrosshair = True
            yScaleOffset = 3
            # @see https://github.com/plouc/nivo/blob/master/packages/line/index.d.ts#L144
            curve = "natural"
        [[[bar]]]
            enableLabel = False
            isInteractive = True
            yScaleOffset = 3

        # Observation specific settings.
        [[[cloudbase]]]
            yScaleMin = 0
            yScaleOffset = 300
        [[[windDir]]]
            curve = "basis"
            lineWidth = 0
            yScaleMin = 0
            yScaleMax = 360
        [[[windSpeed]]]
            yScaleMin = 0
        [[[windGust]]]
            aggregate_type = "max"
            yScaleMin = 0
        [[[radiation]]]
            curve = "basis"
            yScaleMin = 0
        [[[UV]]]
            aggregate_type = "max"
            curve = "step"
            yScaleMin = 0
            yScaleOffset = 1
        [[[rain]]]
            aggregate_type = "sum"
            yScaleOffset = 0.25
        [[[rainRate]]]
            aggregate_type = "max"
            curve = "linear"
            yScaleMin = 0
            yScaleOffset = 0.25
        [[[outHumidity]]]
            yScaleMin = 0
            yScaleMax = 103
        [[[ET]]]
            aggregate_type = "sum"
            yScaleOffset = 0.02
        [[[pressure]]]
            yScaleOffset = 1
        [[[barometer]]]
            yScaleOffset = 1
        [[[altimeter]]]
            yScaleOffset = 1

        # Context specific settings, alltime: if not set, will be calculated.
        [[[day]]]
            aggregate_interval = 1800 # 30 minutes
            [[[[ET]]]]
                aggregate_interval = 7200  # 2 hours
            [[[[rain]]]]
                aggregate_interval = 7200  # 2 hours

        [[[week]]]
            aggregate_interval = 7200  # 2 hours
            [[[[ET]]]]
                aggregate_interval = 86400  # 1 day
            [[[[rain]]]]
                aggregate_interval = 86400  # 1 day

        [[[month]]]
            aggregate_interval = 21600  # 6 hours
            [[[[ET]]]]
                aggregate_interval = 172800  # 2 days
            [[[[rain]]]]
                aggregate_interval = 172800  # 2 days

        [[[year]]]
            aggregate_interval = 172800  # 2 days
            [[[[ET]]]]
                aggregate_interval = 1555200  # 8 days
            [[[[rain]]]]
                aggregate_interval = 1555200  # 8 days

        # Diagram heights.
        [[[heights]]]
            [[[[classic]]]]
                height = "220px"
                height_md = "300px"
                height_lg = "250px"
                height_xlg = "225px"
                height_max = "225px"
            [[[[alternative]]]]
                height = "220px"
                height_md = "325px"
                height_lg = "325px"
                height_xlg = "250px"
                height_max = "250px"

[CheetahGenerator]
    encoding = html_entities
    search_list_extensions = user.weewx_wdc.WdcGeneralUtil, user.weewx_wdc.WdcStatsUtil, user.weewx_wdc.WdcDiagramUtil, user.weewx_wdc.WdcCelestialUtil, user.weewx_wdc.WdcArchiveUtil, user.weewx_wdc.WdcTableUtil

    [[SummaryByMonth]]
        # Reports that summarize "by month"
        [[[NOAA_month]]]
            encoding = normalized_ascii
            template = NOAA/NOAA-%Y-%m.txt.tmpl
            #stale_age = 3600 # Every hour
        [[[summary_month]]]
            template = month-%Y-%m.html.tmpl
            #stale_age = 3600 # Every hour

    [[SummaryByYear]]
        # Reports that summarize "by year"
        [[[NOAA_year]]]
            encoding = normalized_ascii
            template = NOAA/NOAA-%Y.txt.tmpl
            #stale_age = 3600 # Every hour
        [[[summary_year]]]
            template = year-%Y.html.tmpl
            #stale_age = 3600 # Every hour

    # Reports that show statistics "to date", such as day-to-date,
    # week-to-date, month-to-date, etc.
    [[ToDate]]
        [[[day]]]
            template = index.html.tmpl

        [[[yesterday]]]
            template = yesterday.html.tmpl

        [[[week]]]
            template = week.html.tmpl

        [[[month]]]
            template = month.html.tmpl

        [[[year]]]
            template = year.html.tmpl
            #stale_age = 3600 # Every hour

        [[[statistics]]]
            template = statistics.html.tmpl
            stale_age = 43200 # Twice a day

        [[[celestial]]]
            template = celestial.html.tmpl

    # Static pages, add as many as you want.
    [[Static]]
        #[[[about]]]
            #template = about.html.tmpl
            #title = About
        [[[DWD]]]
            template = dwd.html.tmpl
            title = Vorhersage vom DWD

[Units]
    [[TimeFormats]]
        # @see https://weewx.com/docs/customizing.htm#Units_TimeFormats
        day        = %X
        week       = %x
        month      = %x
        year       = %x
        rainyear   = %x
        current    = %x %X
        ephem_day  = %X
        ephem_year = %x
        stats      = %x %X

[CopyGenerator]
    copy_once = dist/main.js, dist/main.css, plotly-custom-build.min.js, favicon.ico, manifest.json, icon-192x192.png, icon-256x256.png, icon-384x384.png, icon-512x512.png, service-worker.js, offline.html
    copy_always = dwd/bwk_bodendruck_na_ana.png, dwd/SchilderLZ.jpg, dwd/bwk_bodendruck_weu_ana.png

[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator

**Comment by Daveiano** [comment]
Hello there :)

I had a quick look over your webpage at https://www.juergen-ernst.com/bhw/index.html and I can see the diagrams!? It looks like you already solved the issue?

**Comment by jernst01** [comment]
Yes I did in the meantime.
Thanks

**Comment by Daveiano** [comment]
Could you share the reason for your problem? Eventually, others could profit from that.

**Comment by jernst01** [comment]
Sure, it was the standard problem ........ Cache in Chrome ........

**Comment by Daveiano** [comment]
Well yes, the cache... Glad it was only the cache!
